// <auto-generated />
using System;
using ClinicAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250421142914_Add-DataSeeding")]
    partial class AddDataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicAPI.Models.Domain.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PatientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b77b84f-42f0-4efd-b35c-290b75caabcb"),
                            Date = "2025-05-01",
                            DoctorId = new Guid("aa0c65cf-a02e-4674-8422-3f713f6632f2"),
                            PatientId = "52cbe818-dd65-46ce-8764-830a3d9008f6",
                            State = "Scheduled",
                            Time = "9:00 AM"
                        },
                        new
                        {
                            Id = new Guid("f4d86dcb-838c-4d6b-93e0-dde2f1a5ebae"),
                            Date = "2025-05-02",
                            DoctorId = new Guid("1d67eaef-637d-47b3-b6f4-3914e5e07472"),
                            PatientId = "0df249dc-078d-4f0a-9709-d3f628d5fce7",
                            State = "Scheduled",
                            Time = "10:00 AM"
                        },
                        new
                        {
                            Id = new Guid("1caad92d-bac0-4527-b80f-7ea7cf0ea111"),
                            Date = "2025-05-03",
                            DoctorId = new Guid("6ca827fc-10f0-4329-85a6-a25916ba22ac"),
                            PatientId = "29e30fb1-8998-4b05-adeb-5a75884e2aca",
                            State = "Scheduled",
                            Time = "11:00 AM"
                        },
                        new
                        {
                            Id = new Guid("2a64bbf9-583f-4112-966f-d46740a872bc"),
                            Date = "2025-05-04",
                            DoctorId = new Guid("eae35e10-9825-4944-adfa-9961a25d6f55"),
                            PatientId = "29cb3ec1-e138-439b-9128-922bf2b3c338",
                            State = "Scheduled",
                            Time = "12:00 AM"
                        },
                        new
                        {
                            Id = new Guid("fe7462a6-f917-4d32-b742-3e67ea67a3e4"),
                            Date = "2025-05-05",
                            DoctorId = new Guid("428d16f9-acc5-477e-8157-484d88e54c7e"),
                            PatientId = "9f1d1b06-f65f-49e9-96e4-4c2b73b83983",
                            State = "Scheduled",
                            Time = "13:00 AM"
                        },
                        new
                        {
                            Id = new Guid("9ee67f13-e69d-41cd-9cb7-7aa6a8725f7e"),
                            Date = "2025-05-06",
                            DoctorId = new Guid("e25eff5e-9a84-478e-ac04-ee5567fde919"),
                            PatientId = "a05a6664-68b9-48ff-a760-42b2f5b16e7f",
                            State = "Scheduled",
                            Time = "14:00 AM"
                        },
                        new
                        {
                            Id = new Guid("3731761a-ebb4-4f64-a520-f98f9cac23e6"),
                            Date = "2025-05-07",
                            DoctorId = new Guid("cab0f693-2a97-43d2-bee3-01e4da18a12d"),
                            PatientId = "f8962ac8-7736-429c-8370-b6a5706114c5",
                            State = "Scheduled",
                            Time = "15:00 AM"
                        },
                        new
                        {
                            Id = new Guid("9501cc24-b228-4837-8f9b-8bfe9de64832"),
                            Date = "2025-05-08",
                            DoctorId = new Guid("9ea2cd4a-2c48-429a-b04a-c48a58c977d8"),
                            PatientId = "ae9e4a55-1221-440a-9e81-26436f64666a",
                            State = "Scheduled",
                            Time = "16:00 AM"
                        },
                        new
                        {
                            Id = new Guid("36218d0f-f9b6-4246-84b2-d78c1bd75b02"),
                            Date = "2025-05-09",
                            DoctorId = new Guid("06d45262-87d8-4219-bb23-8acff618d7f5"),
                            PatientId = "82624f06-56f4-49c8-84e4-dc5bb33c5247",
                            State = "Scheduled",
                            Time = "17:00 AM"
                        },
                        new
                        {
                            Id = new Guid("212a8a00-70ea-4ddd-afb7-e034e65148be"),
                            Date = "2025-05-10",
                            DoctorId = new Guid("34a5d994-d051-4f61-936c-8a9851f8b7d6"),
                            PatientId = "507c3fc0-7ba1-45b6-8f4e-70daeee6a87b",
                            State = "Scheduled",
                            Time = "18:00 AM"
                        },
                        new
                        {
                            Id = new Guid("f31a040b-2eb0-4661-9d58-3c3fbffd6402"),
                            Date = "2025-05-11",
                            DoctorId = new Guid("1c164853-7e4d-4afa-9ad8-9fe98385802e"),
                            PatientId = "1c63783b-affc-40f1-9d4f-f4d4593ff09d",
                            State = "Scheduled",
                            Time = "19:00 AM"
                        },
                        new
                        {
                            Id = new Guid("4a9aa06f-481e-42a3-9102-780c16504f88"),
                            Date = "2025-05-12",
                            DoctorId = new Guid("457be12e-9fcf-4509-a7ac-fe97a46229a6"),
                            PatientId = "26f898b8-0deb-4ba9-8058-354a737a4687",
                            State = "Scheduled",
                            Time = "20:00 AM"
                        },
                        new
                        {
                            Id = new Guid("e2c9aec5-98bf-45b3-a9df-ab27262dc4b3"),
                            Date = "2025-05-13",
                            DoctorId = new Guid("58e9b0ca-4cb2-40b1-a834-ba50ee16b3df"),
                            PatientId = "cbff071f-b407-4dd2-a5c5-e4381cf5a5b7",
                            State = "Scheduled",
                            Time = "9:00 AM"
                        },
                        new
                        {
                            Id = new Guid("6e897d9a-896d-469b-8243-886bb116ea3d"),
                            Date = "2025-05-14",
                            DoctorId = new Guid("4d186b3c-69a4-4956-9657-49b81ad7938e"),
                            PatientId = "4319c960-bf8a-4a56-8591-ac477d434d0e",
                            State = "Scheduled",
                            Time = "10:00 AM"
                        },
                        new
                        {
                            Id = new Guid("825ed25d-b7e1-4a69-bd8d-3d23678adc38"),
                            Date = "2025-05-15",
                            DoctorId = new Guid("7426cc31-387c-4357-b0f3-05c06b3e57ce"),
                            PatientId = "ca9d8238-f49e-46e1-a9d7-9f5dc745e22c",
                            State = "Scheduled",
                            Time = "11:00 AM"
                        },
                        new
                        {
                            Id = new Guid("9c45c14e-3653-43f8-a411-e43b4a1d58f7"),
                            Date = "2025-05-16",
                            DoctorId = new Guid("79c290a0-dcce-4ecc-be7a-7b841e83ea09"),
                            PatientId = "0b1b1a02-ff25-46e8-add7-b55bc94596db",
                            State = "Scheduled",
                            Time = "12:00 AM"
                        },
                        new
                        {
                            Id = new Guid("a2a3c34d-54f5-4ea2-b3a6-35e9d03b41bb"),
                            Date = "2025-05-17",
                            DoctorId = new Guid("5fca8307-11e7-48c3-9f30-d36c205ffb58"),
                            PatientId = "31a5d5ca-755b-4295-a6b5-1c6e90a4f051",
                            State = "Scheduled",
                            Time = "13:00 AM"
                        },
                        new
                        {
                            Id = new Guid("bea03a0a-a2e0-4781-b423-d42860218600"),
                            Date = "2025-05-18",
                            DoctorId = new Guid("1a2f49ba-da0e-4535-a79e-cc158fce99c1"),
                            PatientId = "e8d1902f-57d2-4718-85c7-1cf5f0a1ca18",
                            State = "Scheduled",
                            Time = "14:00 AM"
                        },
                        new
                        {
                            Id = new Guid("e6345352-3410-464c-8578-0f5e2ef83cfe"),
                            Date = "2025-05-19",
                            DoctorId = new Guid("2a0b83bf-316d-4bf4-b4a1-c9951bf23464"),
                            PatientId = "f6c65f86-cf25-455b-b8e9-cf7ce3da6616",
                            State = "Scheduled",
                            Time = "15:00 AM"
                        },
                        new
                        {
                            Id = new Guid("f4ea6c65-2b12-4690-8b95-887f9ea4ffe3"),
                            Date = "2025-05-20",
                            DoctorId = new Guid("622131d6-49bc-40a4-848c-41af48f51b48"),
                            PatientId = "66f7c3ff-cf5d-4022-9d03-4bcefc1e0a25",
                            State = "Scheduled",
                            Time = "16:00 AM"
                        });
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa0c65cf-a02e-4674-8422-3f713f6632f2"),
                            Price = 101.0,
                            Specialty = "Specialty 1",
                            UserId = "ee9464c4-72dd-487e-abae-f28eb1f283d6"
                        },
                        new
                        {
                            Id = new Guid("1d67eaef-637d-47b3-b6f4-3914e5e07472"),
                            Price = 102.0,
                            Specialty = "Specialty 2",
                            UserId = "d329a52a-f062-483b-8ee0-5ee8bddec3cd"
                        },
                        new
                        {
                            Id = new Guid("6ca827fc-10f0-4329-85a6-a25916ba22ac"),
                            Price = 103.0,
                            Specialty = "Specialty 3",
                            UserId = "a3d69e15-a1a0-40b7-b29d-4c509ef3abb2"
                        },
                        new
                        {
                            Id = new Guid("eae35e10-9825-4944-adfa-9961a25d6f55"),
                            Price = 104.0,
                            Specialty = "Specialty 4",
                            UserId = "06ef133d-a03d-4045-9dff-03ba2353c36b"
                        },
                        new
                        {
                            Id = new Guid("428d16f9-acc5-477e-8157-484d88e54c7e"),
                            Price = 105.0,
                            Specialty = "Specialty 5",
                            UserId = "640ba30c-0831-4e9d-b677-fc4dbd052882"
                        },
                        new
                        {
                            Id = new Guid("e25eff5e-9a84-478e-ac04-ee5567fde919"),
                            Price = 106.0,
                            Specialty = "Specialty 6",
                            UserId = "93b598d1-17b3-427f-9488-a1e9e998aa6c"
                        },
                        new
                        {
                            Id = new Guid("cab0f693-2a97-43d2-bee3-01e4da18a12d"),
                            Price = 107.0,
                            Specialty = "Specialty 7",
                            UserId = "88f16ccb-22ec-44f0-9f07-092241c4643c"
                        },
                        new
                        {
                            Id = new Guid("9ea2cd4a-2c48-429a-b04a-c48a58c977d8"),
                            Price = 108.0,
                            Specialty = "Specialty 8",
                            UserId = "670ab904-39e1-4d71-b77d-9058c4fb3826"
                        },
                        new
                        {
                            Id = new Guid("06d45262-87d8-4219-bb23-8acff618d7f5"),
                            Price = 109.0,
                            Specialty = "Specialty 9",
                            UserId = "1e6e6d31-1208-4254-84a0-666ef240af48"
                        },
                        new
                        {
                            Id = new Guid("34a5d994-d051-4f61-936c-8a9851f8b7d6"),
                            Price = 110.0,
                            Specialty = "Specialty 10",
                            UserId = "1d74cdaa-fe65-4358-88c6-cd1d2eeb86b4"
                        },
                        new
                        {
                            Id = new Guid("1c164853-7e4d-4afa-9ad8-9fe98385802e"),
                            Price = 111.0,
                            Specialty = "Specialty 11",
                            UserId = "39f173ee-43e0-4b2d-a5bd-973e513472cc"
                        },
                        new
                        {
                            Id = new Guid("457be12e-9fcf-4509-a7ac-fe97a46229a6"),
                            Price = 112.0,
                            Specialty = "Specialty 12",
                            UserId = "38d495e2-af91-4b97-89e1-60827bb63a24"
                        },
                        new
                        {
                            Id = new Guid("58e9b0ca-4cb2-40b1-a834-ba50ee16b3df"),
                            Price = 113.0,
                            Specialty = "Specialty 13",
                            UserId = "73e422a2-ff2d-40da-ae75-82c96d3d0778"
                        },
                        new
                        {
                            Id = new Guid("4d186b3c-69a4-4956-9657-49b81ad7938e"),
                            Price = 114.0,
                            Specialty = "Specialty 14",
                            UserId = "1e7230ac-2344-47e4-b698-ef958bc93868"
                        },
                        new
                        {
                            Id = new Guid("7426cc31-387c-4357-b0f3-05c06b3e57ce"),
                            Price = 115.0,
                            Specialty = "Specialty 15",
                            UserId = "1660ddf2-fc20-40ae-a0e0-a9b3c6ef1489"
                        },
                        new
                        {
                            Id = new Guid("79c290a0-dcce-4ecc-be7a-7b841e83ea09"),
                            Price = 116.0,
                            Specialty = "Specialty 16",
                            UserId = "b2b74884-dc36-40af-a889-de4b0d44030a"
                        },
                        new
                        {
                            Id = new Guid("5fca8307-11e7-48c3-9f30-d36c205ffb58"),
                            Price = 117.0,
                            Specialty = "Specialty 17",
                            UserId = "b7041f80-6512-4fa9-b99e-7fa037fe1383"
                        },
                        new
                        {
                            Id = new Guid("1a2f49ba-da0e-4535-a79e-cc158fce99c1"),
                            Price = 118.0,
                            Specialty = "Specialty 18",
                            UserId = "1db9741a-8ead-4416-8207-d6ed26176eb9"
                        },
                        new
                        {
                            Id = new Guid("2a0b83bf-316d-4bf4-b4a1-c9951bf23464"),
                            Price = 119.0,
                            Specialty = "Specialty 19",
                            UserId = "c7758f2b-c854-4002-b334-1700df4c9a96"
                        },
                        new
                        {
                            Id = new Guid("622131d6-49bc-40a4-848c-41af48f51b48"),
                            Price = 120.0,
                            Specialty = "Specialty 20",
                            UserId = "2db8c815-4497-4a2c-9567-eb555115d05b"
                        });
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.FileImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("FileLength")
                        .HasColumnType("float");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PrescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId")
                        .IsUnique()
                        .HasFilter("[DoctorId] IS NOT NULL");

                    b.HasIndex("PrescriptionId")
                        .IsUnique()
                        .HasFilter("[PrescriptionId] IS NOT NULL");

                    b.ToTable("FileImages");
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modification_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("37ecd7c3-ca7f-41af-b336-818aad0d2ac0"),
                            AppointmentId = new Guid("4b77b84f-42f0-4efd-b35c-290b75caabcb"),
                            Description = "Prescription for appointment 1",
                            Modification_date = "2025-04-21"
                        },
                        new
                        {
                            Id = new Guid("8e74b5c0-da63-4131-8957-29d690e2974e"),
                            AppointmentId = new Guid("f4d86dcb-838c-4d6b-93e0-dde2f1a5ebae"),
                            Description = "Prescription for appointment 2",
                            Modification_date = "2025-04-21"
                        },
                        new
                        {
                            Id = new Guid("1c8f1052-d43c-445c-a644-78af76fcbd40"),
                            AppointmentId = new Guid("1caad92d-bac0-4527-b80f-7ea7cf0ea111"),
                            Description = "Prescription for appointment 3",
                            Modification_date = "2025-04-21"
                        },
                        new
                        {
                            Id = new Guid("06fb88b0-a3f4-4695-86e7-a6a55d7d1381"),
                            AppointmentId = new Guid("2a64bbf9-583f-4112-966f-d46740a872bc"),
                            Description = "Prescription for appointment 4",
                            Modification_date = "2025-04-21"
                        },
                        new
                        {
                            Id = new Guid("bb84d3e2-f9c5-4bb3-80ca-ecea4332613a"),
                            AppointmentId = new Guid("fe7462a6-f917-4d32-b742-3e67ea67a3e4"),
                            Description = "Prescription for appointment 5",
                            Modification_date = "2025-04-21"
                        },
                        new
                        {
                            Id = new Guid("186bb93b-1d1e-4653-b9ab-8dd17952fe54"),
                            AppointmentId = new Guid("9ee67f13-e69d-41cd-9cb7-7aa6a8725f7e"),
                            Description = "Prescription for appointment 6",
                            Modification_date = "2025-04-21"
                        },
                        new
                        {
                            Id = new Guid("d9355738-e01a-4c49-8b4a-12d5885ec39c"),
                            AppointmentId = new Guid("3731761a-ebb4-4f64-a520-f98f9cac23e6"),
                            Description = "Prescription for appointment 7",
                            Modification_date = "2025-04-21"
                        },
                        new
                        {
                            Id = new Guid("35aa7d28-c3fa-4009-91d9-02e92fb697a5"),
                            AppointmentId = new Guid("9501cc24-b228-4837-8f9b-8bfe9de64832"),
                            Description = "Prescription for appointment 8",
                            Modification_date = "2025-04-21"
                        },
                        new
                        {
                            Id = new Guid("fbc09132-f975-4c50-8dd2-34851d46c601"),
                            AppointmentId = new Guid("36218d0f-f9b6-4246-84b2-d78c1bd75b02"),
                            Description = "Prescription for appointment 9",
                            Modification_date = "2025-04-21"
                        },
                        new
                        {
                            Id = new Guid("171772ac-4f55-4352-acd3-984fc24fd21e"),
                            AppointmentId = new Guid("212a8a00-70ea-4ddd-afb7-e034e65148be"),
                            Description = "Prescription for appointment 10",
                            Modification_date = "2025-04-21"
                        },
                        new
                        {
                            Id = new Guid("ccb9531f-d8a5-4d06-bb7f-4a29951dfb2c"),
                            AppointmentId = new Guid("f31a040b-2eb0-4661-9d58-3c3fbffd6402"),
                            Description = "Prescription for appointment 11",
                            Modification_date = "2025-04-21"
                        },
                        new
                        {
                            Id = new Guid("7acb50e7-40ac-4b1f-a0a2-e21f6e4a0133"),
                            AppointmentId = new Guid("4a9aa06f-481e-42a3-9102-780c16504f88"),
                            Description = "Prescription for appointment 12",
                            Modification_date = "2025-04-21"
                        },
                        new
                        {
                            Id = new Guid("0a4e6800-29f9-4ea8-acda-762843d1a5e7"),
                            AppointmentId = new Guid("e2c9aec5-98bf-45b3-a9df-ab27262dc4b3"),
                            Description = "Prescription for appointment 13",
                            Modification_date = "2025-04-21"
                        },
                        new
                        {
                            Id = new Guid("51316038-270f-4515-81d2-a6aa49fea6f3"),
                            AppointmentId = new Guid("6e897d9a-896d-469b-8243-886bb116ea3d"),
                            Description = "Prescription for appointment 14",
                            Modification_date = "2025-04-21"
                        },
                        new
                        {
                            Id = new Guid("07c58e22-edfb-4862-a5a6-fe67fef640b6"),
                            AppointmentId = new Guid("825ed25d-b7e1-4a69-bd8d-3d23678adc38"),
                            Description = "Prescription for appointment 15",
                            Modification_date = "2025-04-21"
                        },
                        new
                        {
                            Id = new Guid("ff3bc475-cf1e-4581-8d30-de2155f3799f"),
                            AppointmentId = new Guid("9c45c14e-3653-43f8-a411-e43b4a1d58f7"),
                            Description = "Prescription for appointment 16",
                            Modification_date = "2025-04-21"
                        },
                        new
                        {
                            Id = new Guid("a1a09032-f9fb-4e70-9a61-18299f48912f"),
                            AppointmentId = new Guid("a2a3c34d-54f5-4ea2-b3a6-35e9d03b41bb"),
                            Description = "Prescription for appointment 17",
                            Modification_date = "2025-04-21"
                        },
                        new
                        {
                            Id = new Guid("ee977b97-7362-4eb1-aac8-c2de724a2f5d"),
                            AppointmentId = new Guid("bea03a0a-a2e0-4781-b423-d42860218600"),
                            Description = "Prescription for appointment 18",
                            Modification_date = "2025-04-21"
                        },
                        new
                        {
                            Id = new Guid("7c4a3156-2e4e-45bc-9def-94c35f2d39d7"),
                            AppointmentId = new Guid("e6345352-3410-464c-8578-0f5e2ef83cfe"),
                            Description = "Prescription for appointment 19",
                            Modification_date = "2025-04-21"
                        },
                        new
                        {
                            Id = new Guid("8fc62aee-d315-459f-84ab-224e37f95ba8"),
                            AppointmentId = new Guid("f4ea6c65-2b12-4690-8b95-887f9ea4ffe3"),
                            Description = "Prescription for appointment 20",
                            Modification_date = "2025-04-21"
                        });
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.UserApplication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "52cbe818-dd65-46ce-8764-830a3d9008f6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4e8d966a-02f0-4978-9f98-2a28848574d9",
                            Email = "patient1@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT1@CLINIC.COM",
                            NormalizedUserName = "PATIENT1@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFzta9Vkotow/DhK5F3bab23pPMx0B3yloqUarzheWlSELqD5XZ+TQqyd+fUnKaDFw==",
                            PhoneNumber = "01000000001",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "3ffbc2c3-aedb-46eb-b807-18afee10835c",
                            TwoFactorEnabled = false,
                            UserName = "patient1@clinic.com"
                        },
                        new
                        {
                            Id = "0df249dc-078d-4f0a-9709-d3f628d5fce7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "128c13c5-0c34-4e1c-9420-60297984e720",
                            Email = "patient2@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT2@CLINIC.COM",
                            NormalizedUserName = "PATIENT2@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKtvb8JjoKfZAmjg6EYWU+eWrM+1CVlreLBHyXIJW/fOM5Sn0i2XUi+Xe4G9rZvLeg==",
                            PhoneNumber = "01000000002",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "22169dbf-42a6-41ae-8712-218d8612381e",
                            TwoFactorEnabled = false,
                            UserName = "patient2@clinic.com"
                        },
                        new
                        {
                            Id = "29e30fb1-8998-4b05-adeb-5a75884e2aca",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a589b910-4b17-487b-9014-cb9ead2478b8",
                            Email = "patient3@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT3@CLINIC.COM",
                            NormalizedUserName = "PATIENT3@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPFADMai7cqKo9PkgkwUtHzSfXX24RjKSXeptM4lwBI0BJB3EM7kvHU7hLHqFE45Hg==",
                            PhoneNumber = "01000000003",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "701117d2-88d6-4ff9-9d92-5c8fd85ebd98",
                            TwoFactorEnabled = false,
                            UserName = "patient3@clinic.com"
                        },
                        new
                        {
                            Id = "29cb3ec1-e138-439b-9128-922bf2b3c338",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cc0be3d8-9881-4483-a07d-a969980cb046",
                            Email = "patient4@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT4@CLINIC.COM",
                            NormalizedUserName = "PATIENT4@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAYL+J61EsgX903JLM8WXK4bOr7kdsvIXp8IwtyTUjpbQk9wKeuARZ3XFXWPnSeQBg==",
                            PhoneNumber = "01000000004",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "6edd982e-f0f7-44fc-b817-61c2332fd40b",
                            TwoFactorEnabled = false,
                            UserName = "patient4@clinic.com"
                        },
                        new
                        {
                            Id = "9f1d1b06-f65f-49e9-96e4-4c2b73b83983",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "02cb0b7d-b2c1-4285-b8af-b71ab8fd7fa1",
                            Email = "patient5@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT5@CLINIC.COM",
                            NormalizedUserName = "PATIENT5@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHrsP2nEb65mWDXjgFtlrku8mGMY7Mjmf4w1vh+PLwApHR4qFz+xdD+ZD9S9CvNlgA==",
                            PhoneNumber = "01000000005",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "87589296-abd8-4786-a258-5d764e1d20ba",
                            TwoFactorEnabled = false,
                            UserName = "patient5@clinic.com"
                        },
                        new
                        {
                            Id = "a05a6664-68b9-48ff-a760-42b2f5b16e7f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "874e58f7-d9f2-4324-978f-26491611353f",
                            Email = "patient6@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT6@CLINIC.COM",
                            NormalizedUserName = "PATIENT6@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMlEebxbXx1FfkV9GdUAohp0/KLOhtt1uNW9idrxHJ+apSG3gMC8NJNcgUJOS7Z0xw==",
                            PhoneNumber = "01000000006",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1ba3727d-7fa3-48c2-927d-09118c46b36a",
                            TwoFactorEnabled = false,
                            UserName = "patient6@clinic.com"
                        },
                        new
                        {
                            Id = "f8962ac8-7736-429c-8370-b6a5706114c5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d81c072c-db3b-4e0e-86cb-16ae464b622a",
                            Email = "patient7@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT7@CLINIC.COM",
                            NormalizedUserName = "PATIENT7@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENUvvdyNj9ZjrMDzdP9ku+j3+S0muUMZjcScYFkniBfaTxoRHu5ZkTnTW1NABX6JDg==",
                            PhoneNumber = "01000000007",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "0df2a937-368d-4667-a4ee-08cb2bfce631",
                            TwoFactorEnabled = false,
                            UserName = "patient7@clinic.com"
                        },
                        new
                        {
                            Id = "ae9e4a55-1221-440a-9e81-26436f64666a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "58c95c23-896d-41c2-b12c-93fdc1e0f1c9",
                            Email = "patient8@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT8@CLINIC.COM",
                            NormalizedUserName = "PATIENT8@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDmi/tp6KawMhkSn8X931acEZA2YjSR15vz864RCa3lESdxjg5EQO+xGhMnM5Udr+A==",
                            PhoneNumber = "01000000008",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1214581b-1017-4677-9a6c-996b6ae9cb96",
                            TwoFactorEnabled = false,
                            UserName = "patient8@clinic.com"
                        },
                        new
                        {
                            Id = "82624f06-56f4-49c8-84e4-dc5bb33c5247",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7d41cd5f-aae2-4ba3-b0d1-014713a3f309",
                            Email = "patient9@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT9@CLINIC.COM",
                            NormalizedUserName = "PATIENT9@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAED1Aoh4DoWnt+YAmnJ5T1kfANgK35FWYCVEo44pCevFbxKeC5B5APhuyCi9ArNt9IA==",
                            PhoneNumber = "01000000009",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "50ffae3c-cdb6-46e8-9f6f-076fce39d3ce",
                            TwoFactorEnabled = false,
                            UserName = "patient9@clinic.com"
                        },
                        new
                        {
                            Id = "507c3fc0-7ba1-45b6-8f4e-70daeee6a87b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e937187c-a7e3-4aa1-a988-14e9c2d1964e",
                            Email = "patient10@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT10@CLINIC.COM",
                            NormalizedUserName = "PATIENT10@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPvINf1CzJW1nLC4tJZG9te7LuqCRW9OrDBb1+Dozp3cNJuwlgkcX6lzVZtTqfhN4g==",
                            PhoneNumber = "01000000010",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1f6cd537-def2-430c-8ec9-cd459cf55788",
                            TwoFactorEnabled = false,
                            UserName = "patient10@clinic.com"
                        },
                        new
                        {
                            Id = "1c63783b-affc-40f1-9d4f-f4d4593ff09d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f2f8a9b4-858e-4e5d-9bee-dda8f082b60f",
                            Email = "patient11@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT11@CLINIC.COM",
                            NormalizedUserName = "PATIENT11@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECsLNfA4H0HIgM+Eo7q0ar7gAEYu8TIG/kAZkM+nP9H5X1O0bwxHn2AW6AJaNgmBUQ==",
                            PhoneNumber = "01000000011",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "62389492-e0b6-4a77-878e-285d38c8367d",
                            TwoFactorEnabled = false,
                            UserName = "patient11@clinic.com"
                        },
                        new
                        {
                            Id = "26f898b8-0deb-4ba9-8058-354a737a4687",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "11ce92eb-ab87-46a8-8c01-7a740c52855e",
                            Email = "patient12@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT12@CLINIC.COM",
                            NormalizedUserName = "PATIENT12@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIM5UV0a3QBf6zvWzS/0yHAwEX3XLcRv0Y2bkvgZtMxxmACWVJ9Y5fXILnLXkIAhWA==",
                            PhoneNumber = "01000000012",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "070da9fb-4d83-4d74-a3f8-751ba83e4bb4",
                            TwoFactorEnabled = false,
                            UserName = "patient12@clinic.com"
                        },
                        new
                        {
                            Id = "cbff071f-b407-4dd2-a5c5-e4381cf5a5b7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ea9b5b07-a029-489e-bfb7-3e4df326de5b",
                            Email = "patient13@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT13@CLINIC.COM",
                            NormalizedUserName = "PATIENT13@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHUx6ZfKzY5mztNjofoKuZPPqi6JuXsY2wF7UO7FM9F65XxhLJLkiaqUO+uENbvl1A==",
                            PhoneNumber = "01000000013",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "02cba3b7-4e82-4e13-99b8-5a8de1272601",
                            TwoFactorEnabled = false,
                            UserName = "patient13@clinic.com"
                        },
                        new
                        {
                            Id = "4319c960-bf8a-4a56-8591-ac477d434d0e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8244cafe-fb42-48d7-9b51-1c26f28ec469",
                            Email = "patient14@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT14@CLINIC.COM",
                            NormalizedUserName = "PATIENT14@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDYHMtWghu64alx8zUSwCpZof21/GNA+ptJ+4MRxk5anaCys9nWVCBzA0TGQdERsnw==",
                            PhoneNumber = "01000000014",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "dcf023b0-b6ca-4863-9858-ae2dc7215499",
                            TwoFactorEnabled = false,
                            UserName = "patient14@clinic.com"
                        },
                        new
                        {
                            Id = "ca9d8238-f49e-46e1-a9d7-9f5dc745e22c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "80945fd6-6b0c-4e12-8a5d-2e8af3695f05",
                            Email = "patient15@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT15@CLINIC.COM",
                            NormalizedUserName = "PATIENT15@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOeTo0HH2H6K4etZCNfg0NUGGusvemVTLBHxmJNlK7xiaiIKjCrKjJZSTnTe6gnfOQ==",
                            PhoneNumber = "01000000015",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "5b4c0b81-1303-4a02-afd1-d14626e50eb7",
                            TwoFactorEnabled = false,
                            UserName = "patient15@clinic.com"
                        },
                        new
                        {
                            Id = "0b1b1a02-ff25-46e8-add7-b55bc94596db",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "de088424-62f7-42b6-9719-5d3e35a96f3a",
                            Email = "patient16@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT16@CLINIC.COM",
                            NormalizedUserName = "PATIENT16@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECEwyPIvdfqHQ6EWxzi0uf4mi+Z1YFAZf/XTToVjffnhNjKKi/+O7/VF4vCHwayniQ==",
                            PhoneNumber = "01000000016",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "0ebcffc5-9a3f-4709-ab95-739997005484",
                            TwoFactorEnabled = false,
                            UserName = "patient16@clinic.com"
                        },
                        new
                        {
                            Id = "31a5d5ca-755b-4295-a6b5-1c6e90a4f051",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "42eb0ab5-9888-4881-81f4-3838c3878e45",
                            Email = "patient17@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT17@CLINIC.COM",
                            NormalizedUserName = "PATIENT17@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOx94haA5UYD2TJ39rDdlwQQVrjXlR0PRr5ZTJab6KGS+Mh+ublbNMyfqZp8LA4xKQ==",
                            PhoneNumber = "01000000017",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "608bfba0-afba-484c-9ee7-9b194d126715",
                            TwoFactorEnabled = false,
                            UserName = "patient17@clinic.com"
                        },
                        new
                        {
                            Id = "e8d1902f-57d2-4718-85c7-1cf5f0a1ca18",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2a85c041-7817-4d44-986f-3aacb8d82e56",
                            Email = "patient18@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT18@CLINIC.COM",
                            NormalizedUserName = "PATIENT18@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECAmJkUGHUTe2OfzEMjhyj6pnF4Y/257qc1rabcciNXyQ62ZIkIJ0UAwjYKGBVeBaw==",
                            PhoneNumber = "01000000018",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "27f56009-2bcc-4fb2-9a70-194a7089df5a",
                            TwoFactorEnabled = false,
                            UserName = "patient18@clinic.com"
                        },
                        new
                        {
                            Id = "f6c65f86-cf25-455b-b8e9-cf7ce3da6616",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4b10d7fe-31e4-4d35-97ef-be504b3650ab",
                            Email = "patient19@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT19@CLINIC.COM",
                            NormalizedUserName = "PATIENT19@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPPNs1b+O90DbHLJEmusWt2jvxlcNknoiAM5sZH1u0DoMWT76OODWIGB8SR+I8chvg==",
                            PhoneNumber = "01000000019",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "713657b5-4226-4b00-9ec5-2b1b4308da7a",
                            TwoFactorEnabled = false,
                            UserName = "patient19@clinic.com"
                        },
                        new
                        {
                            Id = "66f7c3ff-cf5d-4022-9d03-4bcefc1e0a25",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "33e84adb-3475-4c47-8dc2-068a43c73cc5",
                            Email = "patient20@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT20@CLINIC.COM",
                            NormalizedUserName = "PATIENT20@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENgbcqQi8NxZmgjrbIvzpnrOJI0J58zDjVd2soxI20Yw2jYZNKZcMagIa+oLXHkHVQ==",
                            PhoneNumber = "01000000020",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "536884c9-e0fb-4caf-ac0b-50675eaa7e08",
                            TwoFactorEnabled = false,
                            UserName = "patient20@clinic.com"
                        },
                        new
                        {
                            Id = "ee9464c4-72dd-487e-abae-f28eb1f283d6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5fdf2825-8ca6-4fc7-b290-167338d79a49",
                            Email = "doctor1@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR1@CLINIC.COM",
                            NormalizedUserName = "DOCTOR1@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEH9FIkQSclacw1sRNDPzUqJTTYpfA6Cp8q6OLQG4jcrU0DmPZFZ1IuIIy0CJAo2Dg==",
                            PhoneNumber = "01100000001",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "06b3a41a-17d4-4085-8d57-2047412479b9",
                            TwoFactorEnabled = false,
                            UserName = "doctor1@clinic.com"
                        },
                        new
                        {
                            Id = "d329a52a-f062-483b-8ee0-5ee8bddec3cd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "beb8726b-5362-474b-b201-b295c1dda66f",
                            Email = "doctor2@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR2@CLINIC.COM",
                            NormalizedUserName = "DOCTOR2@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHbW1796BbIVXmI6Kbjue0t5hOQNlE3YFTvlQgt2MYjeBSRSZ2ix33ff3z4xDZ3yMw==",
                            PhoneNumber = "01100000002",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "0e5c401e-9a97-4905-adfa-6701a408a6ba",
                            TwoFactorEnabled = false,
                            UserName = "doctor2@clinic.com"
                        },
                        new
                        {
                            Id = "a3d69e15-a1a0-40b7-b29d-4c509ef3abb2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f6f6258f-1c67-41b0-8c92-d4473e52146c",
                            Email = "doctor3@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR3@CLINIC.COM",
                            NormalizedUserName = "DOCTOR3@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELJCzyYUTosckjd82FGqXTKcIknOO/DUZoOYxGfoTQSUpV2c8MvJQeUfV4RdwQnPDA==",
                            PhoneNumber = "01100000003",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "e55e3846-7890-4a60-a3aa-0631a89b8648",
                            TwoFactorEnabled = false,
                            UserName = "doctor3@clinic.com"
                        },
                        new
                        {
                            Id = "06ef133d-a03d-4045-9dff-03ba2353c36b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c1d07609-db92-42e2-b53f-72608f3e6b0c",
                            Email = "doctor4@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR4@CLINIC.COM",
                            NormalizedUserName = "DOCTOR4@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKdtNM+/b4XCdHu8RWoY1WAbnHyohQsfqTihsmfbMwkSXiEOtHQBKpUbY5Lum9Tb5Q==",
                            PhoneNumber = "01100000004",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "89825f74-ef07-43d2-938e-0e9ec1b653ee",
                            TwoFactorEnabled = false,
                            UserName = "doctor4@clinic.com"
                        },
                        new
                        {
                            Id = "640ba30c-0831-4e9d-b677-fc4dbd052882",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3e4ffbbc-4db6-41f7-b1de-dbce2cab4a40",
                            Email = "doctor5@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR5@CLINIC.COM",
                            NormalizedUserName = "DOCTOR5@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKw2RV3YRofgdHTzLQshj1UdBOFl+qutPpH+fE+B4+DZMC2eRKV4xJ3tntVHQWa+tg==",
                            PhoneNumber = "01100000005",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "89106df2-17bd-4acd-9ffd-fdc1e04df2fb",
                            TwoFactorEnabled = false,
                            UserName = "doctor5@clinic.com"
                        },
                        new
                        {
                            Id = "93b598d1-17b3-427f-9488-a1e9e998aa6c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "baf573bf-04d5-4007-addc-f2a24a13b257",
                            Email = "doctor6@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR6@CLINIC.COM",
                            NormalizedUserName = "DOCTOR6@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEK+/IaVzgAq3IkDLB/6s0+Ks2p+WcS3fXUNR3DiOXzek4K94M2j/J40tAYWKNmggGA==",
                            PhoneNumber = "01100000006",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "45fe89cf-a991-488f-ac81-168b9cfcc99b",
                            TwoFactorEnabled = false,
                            UserName = "doctor6@clinic.com"
                        },
                        new
                        {
                            Id = "88f16ccb-22ec-44f0-9f07-092241c4643c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e3e04159-007a-415a-bf13-d7fdb6671d66",
                            Email = "doctor7@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR7@CLINIC.COM",
                            NormalizedUserName = "DOCTOR7@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA3tepPwlgP5kCtDrBGQhd5fIm1bawzlDU+EMsg9e73Dh3uERf4kTd+7agAYyTwgEg==",
                            PhoneNumber = "01100000007",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "3fe93ff8-631a-4fd5-8633-857e12968ff9",
                            TwoFactorEnabled = false,
                            UserName = "doctor7@clinic.com"
                        },
                        new
                        {
                            Id = "670ab904-39e1-4d71-b77d-9058c4fb3826",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3fd395c8-6645-49d5-95f2-96860f68f1d6",
                            Email = "doctor8@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR8@CLINIC.COM",
                            NormalizedUserName = "DOCTOR8@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEE8XyVOg94FnQISLycw8qfhH7kC+8TPcC6RRJRdMrzQ+aESyan7pq/gjPZ5u04B5nQ==",
                            PhoneNumber = "01100000008",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "d1761ecc-a690-4bc6-b24f-05926c774d3c",
                            TwoFactorEnabled = false,
                            UserName = "doctor8@clinic.com"
                        },
                        new
                        {
                            Id = "1e6e6d31-1208-4254-84a0-666ef240af48",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ff2be00a-72a8-4d88-afce-11925044e513",
                            Email = "doctor9@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR9@CLINIC.COM",
                            NormalizedUserName = "DOCTOR9@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKU9WQ9BRQskCcAe3crQs8apn1ZFBFUbGohRxskCgFpwUtT8cvv3OilJYhvKm2Y18w==",
                            PhoneNumber = "01100000009",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1182da7d-6cf7-4d5f-8e2d-2ae5fbec150d",
                            TwoFactorEnabled = false,
                            UserName = "doctor9@clinic.com"
                        },
                        new
                        {
                            Id = "1d74cdaa-fe65-4358-88c6-cd1d2eeb86b4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d461a036-2c42-4f87-89f2-8449d64858f1",
                            Email = "doctor10@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR10@CLINIC.COM",
                            NormalizedUserName = "DOCTOR10@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAhMqai3y70YdpwQHSHLvxE77anjuMEEIXeLYPFREo46fj6yNmu5mnzPkWoFhytlcg==",
                            PhoneNumber = "01100000010",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "d7b9ff28-907a-40aa-ae9c-eb118b7386e2",
                            TwoFactorEnabled = false,
                            UserName = "doctor10@clinic.com"
                        },
                        new
                        {
                            Id = "39f173ee-43e0-4b2d-a5bd-973e513472cc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "76582f60-8c9a-49ad-b223-c8a20080a1db",
                            Email = "doctor11@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR11@CLINIC.COM",
                            NormalizedUserName = "DOCTOR11@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFlt4M++I0HONzK1rCgAkT0xBr/dL8Q239WWhQ24n7/P+T7dEqJUgrCQ3ePx4h7uaw==",
                            PhoneNumber = "01100000011",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "ce32660e-74ba-4d57-9d8f-3ecf0f28cc0e",
                            TwoFactorEnabled = false,
                            UserName = "doctor11@clinic.com"
                        },
                        new
                        {
                            Id = "38d495e2-af91-4b97-89e1-60827bb63a24",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5d5aec81-118b-44c5-b9e6-e6710ca73aa3",
                            Email = "doctor12@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR12@CLINIC.COM",
                            NormalizedUserName = "DOCTOR12@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPcLrP7wIk7aKmJ+b/XknrRALoYfU+ZNjk3ulJrTZYWnPFlYkwCi+8d1Q4PXLsDcCg==",
                            PhoneNumber = "01100000012",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "b72ce1ce-3dae-49fd-b613-4999682a7f60",
                            TwoFactorEnabled = false,
                            UserName = "doctor12@clinic.com"
                        },
                        new
                        {
                            Id = "73e422a2-ff2d-40da-ae75-82c96d3d0778",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4d0f517b-bbb7-48b3-8178-968b92f3dcdf",
                            Email = "doctor13@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR13@CLINIC.COM",
                            NormalizedUserName = "DOCTOR13@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOBdqI5cH3FbAEO3eS6+JwyDL0LT0B4PF/873svQIg1/Ft59cmdYcTo4MdyiD9pekA==",
                            PhoneNumber = "01100000013",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "e06b5f55-e0cf-4170-8de3-5aa11d151e23",
                            TwoFactorEnabled = false,
                            UserName = "doctor13@clinic.com"
                        },
                        new
                        {
                            Id = "1e7230ac-2344-47e4-b698-ef958bc93868",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "51e21788-0268-4151-ad16-7fb5af438899",
                            Email = "doctor14@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR14@CLINIC.COM",
                            NormalizedUserName = "DOCTOR14@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELY+KXGKjDwuT+Z4NCVf9GjVTkITuPFaVEqPhD3D9KezIq89y67pSN3uX62fgLI7jw==",
                            PhoneNumber = "01100000014",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "d270558c-c041-4797-b703-678edc240f01",
                            TwoFactorEnabled = false,
                            UserName = "doctor14@clinic.com"
                        },
                        new
                        {
                            Id = "1660ddf2-fc20-40ae-a0e0-a9b3c6ef1489",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c6118e3f-3765-4d07-9dcf-1e5bf937c89c",
                            Email = "doctor15@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR15@CLINIC.COM",
                            NormalizedUserName = "DOCTOR15@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEG90KalWrqOjgNwULu9w6vgFUrqwylxzoGswGGF85muPDXTSi1PjYl/3ikNhBENfQ==",
                            PhoneNumber = "01100000015",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1575e5d6-d9a7-453f-ae39-ca686dfcf357",
                            TwoFactorEnabled = false,
                            UserName = "doctor15@clinic.com"
                        },
                        new
                        {
                            Id = "b2b74884-dc36-40af-a889-de4b0d44030a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "88724701-3765-4751-be4d-17b2e2a299af",
                            Email = "doctor16@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR16@CLINIC.COM",
                            NormalizedUserName = "DOCTOR16@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBjni34urTTGkrFsq17Qmn7pn67rxJ3EfokuzmKVdN5Vy3aG9pY+Z0CGE7wnl3abYA==",
                            PhoneNumber = "01100000016",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "c6ea1e5c-dcc0-4b70-bbac-de88575a6465",
                            TwoFactorEnabled = false,
                            UserName = "doctor16@clinic.com"
                        },
                        new
                        {
                            Id = "b7041f80-6512-4fa9-b99e-7fa037fe1383",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aac5f08a-5f92-4a29-a227-1256be36ae57",
                            Email = "doctor17@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR17@CLINIC.COM",
                            NormalizedUserName = "DOCTOR17@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOff+t8xRvTbLYwz7WOXEjY51P7nqv6KKaVhO7xqRkdwD4JJrxoP1URcY6n+Z7o88w==",
                            PhoneNumber = "01100000017",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "894d24cf-f390-4d4f-a5b1-a0b5345ab57a",
                            TwoFactorEnabled = false,
                            UserName = "doctor17@clinic.com"
                        },
                        new
                        {
                            Id = "1db9741a-8ead-4416-8207-d6ed26176eb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4a49084e-acf1-47fa-8a59-7bb701979287",
                            Email = "doctor18@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR18@CLINIC.COM",
                            NormalizedUserName = "DOCTOR18@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENTQNDISzAXWQotD7xGqZDCzbISVBM0pP9FWsdQ0mO74mSd3CVmMoKdm2gclLTyJtw==",
                            PhoneNumber = "01100000018",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "350c4c62-cfe9-4233-8623-0f7b5fb4ecb6",
                            TwoFactorEnabled = false,
                            UserName = "doctor18@clinic.com"
                        },
                        new
                        {
                            Id = "c7758f2b-c854-4002-b334-1700df4c9a96",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "33bc4a99-7543-4cc5-ba1a-1ea9e8494c95",
                            Email = "doctor19@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR19@CLINIC.COM",
                            NormalizedUserName = "DOCTOR19@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIO6kzJ5tVu/yqfsDpCMBwyEudIIrcyj8xiH1HJKljGFQowCSHSZ3TiuCQKFW1xKAw==",
                            PhoneNumber = "01100000019",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "f13fb049-1755-4bf7-bab6-aa6bcb3eaa2c",
                            TwoFactorEnabled = false,
                            UserName = "doctor19@clinic.com"
                        },
                        new
                        {
                            Id = "2db8c815-4497-4a2c-9567-eb555115d05b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8581b27f-9f84-4bc0-82b3-21cc451399c5",
                            Email = "doctor20@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR20@CLINIC.COM",
                            NormalizedUserName = "DOCTOR20@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIcReBY0oXBfWR32gmKb1X3DGFNTPPdJnp3Ah8k6AAB/hDKv/Iu00H3uGCNcBYMwEQ==",
                            PhoneNumber = "01100000020",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "e353fb85-1620-4659-b95b-1f91d2563fdf",
                            TwoFactorEnabled = false,
                            UserName = "doctor20@clinic.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "675b578c-8739-4b1b-a706-816fb14910bd",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "72235979-4cb2-4bb1-9de9-9e931f98610e",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "52cbe818-dd65-46ce-8764-830a3d9008f6",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "0df249dc-078d-4f0a-9709-d3f628d5fce7",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "29e30fb1-8998-4b05-adeb-5a75884e2aca",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "29cb3ec1-e138-439b-9128-922bf2b3c338",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "9f1d1b06-f65f-49e9-96e4-4c2b73b83983",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "a05a6664-68b9-48ff-a760-42b2f5b16e7f",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "f8962ac8-7736-429c-8370-b6a5706114c5",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "ae9e4a55-1221-440a-9e81-26436f64666a",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "82624f06-56f4-49c8-84e4-dc5bb33c5247",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "507c3fc0-7ba1-45b6-8f4e-70daeee6a87b",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "1c63783b-affc-40f1-9d4f-f4d4593ff09d",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "26f898b8-0deb-4ba9-8058-354a737a4687",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "cbff071f-b407-4dd2-a5c5-e4381cf5a5b7",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "4319c960-bf8a-4a56-8591-ac477d434d0e",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "ca9d8238-f49e-46e1-a9d7-9f5dc745e22c",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "0b1b1a02-ff25-46e8-add7-b55bc94596db",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "31a5d5ca-755b-4295-a6b5-1c6e90a4f051",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "e8d1902f-57d2-4718-85c7-1cf5f0a1ca18",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "f6c65f86-cf25-455b-b8e9-cf7ce3da6616",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "66f7c3ff-cf5d-4022-9d03-4bcefc1e0a25",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "ee9464c4-72dd-487e-abae-f28eb1f283d6",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "d329a52a-f062-483b-8ee0-5ee8bddec3cd",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "a3d69e15-a1a0-40b7-b29d-4c509ef3abb2",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "06ef133d-a03d-4045-9dff-03ba2353c36b",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "640ba30c-0831-4e9d-b677-fc4dbd052882",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "93b598d1-17b3-427f-9488-a1e9e998aa6c",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "88f16ccb-22ec-44f0-9f07-092241c4643c",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "670ab904-39e1-4d71-b77d-9058c4fb3826",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "1e6e6d31-1208-4254-84a0-666ef240af48",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "1d74cdaa-fe65-4358-88c6-cd1d2eeb86b4",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "39f173ee-43e0-4b2d-a5bd-973e513472cc",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "38d495e2-af91-4b97-89e1-60827bb63a24",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "73e422a2-ff2d-40da-ae75-82c96d3d0778",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "1e7230ac-2344-47e4-b698-ef958bc93868",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "1660ddf2-fc20-40ae-a0e0-a9b3c6ef1489",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "b2b74884-dc36-40af-a889-de4b0d44030a",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "b7041f80-6512-4fa9-b99e-7fa037fe1383",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "1db9741a-8ead-4416-8207-d6ed26176eb9",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "c7758f2b-c854-4002-b334-1700df4c9a96",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "2db8c815-4497-4a2c-9567-eb555115d05b",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Appointment", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Doctor", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", "userApplication")
                        .WithOne()
                        .HasForeignKey("ClinicAPI.Models.Domain.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userApplication");
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.FileImage", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.Doctor", "Doctor")
                        .WithOne("FileImage")
                        .HasForeignKey("ClinicAPI.Models.Domain.FileImage", "DoctorId");

                    b.HasOne("ClinicAPI.Models.Domain.Prescription", "Prescription")
                        .WithOne("FileImage")
                        .HasForeignKey("ClinicAPI.Models.Domain.FileImage", "PrescriptionId");

                    b.Navigation("Doctor");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Prescription", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.Appointment", "Appointment")
                        .WithOne("Prescription")
                        .HasForeignKey("ClinicAPI.Models.Domain.Prescription", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Appointment", b =>
                {
                    b.Navigation("Prescription")
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("FileImage")
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Prescription", b =>
                {
                    b.Navigation("FileImage")
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.UserApplication", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
