// <auto-generated />
using System;
using ClinicAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250507012319_FixStatusSeed")]
    partial class FixStatusSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicAPI.Models.Domain.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PatientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d590a5c5-d2e0-4231-ad0f-460e214ef2c9"),
                            Date = "2025-05-01",
                            DoctorId = new Guid("a951df2d-8904-4310-a2c0-7013426b72d8"),
                            PatientId = "4336e0d3-0e62-48b3-81a6-53dff6c072a5",
                            State = "Scheduled",
                            Time = "9:00 AM"
                        },
                        new
                        {
                            Id = new Guid("ac6bd8c4-5e2e-4512-96eb-c14970762902"),
                            Date = "2025-05-02",
                            DoctorId = new Guid("f48df05f-d700-4389-8d67-bdf0cc1d89fa"),
                            PatientId = "b2cb952a-14b7-4bee-9f42-77601734bbc4",
                            State = "Scheduled",
                            Time = "10:00 AM"
                        },
                        new
                        {
                            Id = new Guid("2db9da4e-7b06-44da-b556-358715db152e"),
                            Date = "2025-05-03",
                            DoctorId = new Guid("d123062f-c0b2-4cae-a85c-21553d20079a"),
                            PatientId = "1b0c027e-0fe0-471c-94c0-a4872f1edaa8",
                            State = "Scheduled",
                            Time = "11:00 AM"
                        },
                        new
                        {
                            Id = new Guid("856991e9-6007-4ad7-9083-fea6bc2e1938"),
                            Date = "2025-05-04",
                            DoctorId = new Guid("e3542f97-fe03-44c6-a855-92ebe016718c"),
                            PatientId = "887c3565-09c4-4d6b-b594-0504523f0430",
                            State = "Scheduled",
                            Time = "12:00 AM"
                        },
                        new
                        {
                            Id = new Guid("11e10896-e187-4d5d-aef8-99d7c4a9a72d"),
                            Date = "2025-05-05",
                            DoctorId = new Guid("957d2881-7e24-407a-bb14-62e29d213749"),
                            PatientId = "01fa0d97-457b-41cb-9298-cb8620e5ca9f",
                            State = "Scheduled",
                            Time = "13:00 AM"
                        },
                        new
                        {
                            Id = new Guid("9be8ef20-91e3-442e-a0cb-916c9f12de2d"),
                            Date = "2025-05-06",
                            DoctorId = new Guid("7bd5f392-df1a-4793-abe5-d0ec40ad0a15"),
                            PatientId = "557bbb5c-6368-4ad6-a3bc-e38948632b88",
                            State = "Scheduled",
                            Time = "14:00 AM"
                        },
                        new
                        {
                            Id = new Guid("1ec1c562-d22b-4f8f-83a4-9197570161f1"),
                            Date = "2025-05-07",
                            DoctorId = new Guid("8a8b6077-904d-422d-bc21-d1df2a2cdbe5"),
                            PatientId = "fbaa04e4-ebb4-4cf2-a860-2bf13cd67895",
                            State = "Scheduled",
                            Time = "15:00 AM"
                        },
                        new
                        {
                            Id = new Guid("b50b2eb6-583c-4929-a16f-d2cbca66111e"),
                            Date = "2025-05-08",
                            DoctorId = new Guid("a1eafc54-7b06-4e28-a3b1-8769ab6a2d24"),
                            PatientId = "a63e6d2f-c623-4681-88f7-83c9c4649269",
                            State = "Scheduled",
                            Time = "16:00 AM"
                        },
                        new
                        {
                            Id = new Guid("f982d49b-bd29-4954-abc3-726a85d1b345"),
                            Date = "2025-05-09",
                            DoctorId = new Guid("0b18971d-f8b1-4bcb-a0db-cfafc16bcc5f"),
                            PatientId = "5164ed58-4b9e-47cf-8ec3-096394761f2a",
                            State = "Scheduled",
                            Time = "17:00 AM"
                        },
                        new
                        {
                            Id = new Guid("e78454f6-23aa-44cd-8c7e-14a8b3e60d50"),
                            Date = "2025-05-10",
                            DoctorId = new Guid("5ebfd291-b401-401f-b151-751435847e14"),
                            PatientId = "551b9e2a-a76e-4643-a701-aef28baa6b0d",
                            State = "Scheduled",
                            Time = "18:00 AM"
                        },
                        new
                        {
                            Id = new Guid("61c6df03-612f-4ba3-a0ff-0257828d8e78"),
                            Date = "2025-05-11",
                            DoctorId = new Guid("7f0d600a-ca4d-4245-86ef-2f5ce11f1837"),
                            PatientId = "8bef09fd-e7e2-4146-aa8f-2a632b8b9d2d",
                            State = "Scheduled",
                            Time = "19:00 AM"
                        },
                        new
                        {
                            Id = new Guid("e5055c43-fb32-4f8d-951a-834ceab1494e"),
                            Date = "2025-05-12",
                            DoctorId = new Guid("c1884f2a-a51b-4ffe-98fd-fad5f18e43bb"),
                            PatientId = "a89af95f-b24a-40fe-addf-d34f31925755",
                            State = "Scheduled",
                            Time = "20:00 AM"
                        },
                        new
                        {
                            Id = new Guid("2a97ac11-a908-4057-95f3-7d1a76866bea"),
                            Date = "2025-05-13",
                            DoctorId = new Guid("9e92ed51-7479-47ff-87a7-6ec378eb4ecd"),
                            PatientId = "ef82c308-ada0-4767-ae06-d7be1d85be1f",
                            State = "Scheduled",
                            Time = "9:00 AM"
                        },
                        new
                        {
                            Id = new Guid("07c82a99-37f1-4082-81a3-eff1d4038816"),
                            Date = "2025-05-14",
                            DoctorId = new Guid("d0ac692b-9f0f-4216-91fd-ad837b015339"),
                            PatientId = "fc4b8c77-6015-48a9-be61-3485498c45d6",
                            State = "Scheduled",
                            Time = "10:00 AM"
                        },
                        new
                        {
                            Id = new Guid("1cd0a6cf-ed55-40f3-a647-7c301fa535b4"),
                            Date = "2025-05-15",
                            DoctorId = new Guid("21a48de7-3cc5-4371-9bd9-ae585b771b28"),
                            PatientId = "c3208482-a0e6-4090-88c6-aecda7592bbc",
                            State = "Scheduled",
                            Time = "11:00 AM"
                        },
                        new
                        {
                            Id = new Guid("5a4a9cfd-dcb3-4589-8625-dee975450c88"),
                            Date = "2025-05-16",
                            DoctorId = new Guid("3c35065c-c285-4a7c-8a64-78d9a68b981d"),
                            PatientId = "d5c31600-3ba1-4907-b72b-4d56ef4f68c6",
                            State = "Scheduled",
                            Time = "12:00 AM"
                        },
                        new
                        {
                            Id = new Guid("4fa0c945-6a49-41c6-9616-7b7f63f647b9"),
                            Date = "2025-05-17",
                            DoctorId = new Guid("6d04d0c3-5322-4207-9297-1418ad6384fb"),
                            PatientId = "f3f8c375-0e9f-44d2-9023-8eab65ea9d85",
                            State = "Scheduled",
                            Time = "13:00 AM"
                        },
                        new
                        {
                            Id = new Guid("793688c9-5932-46cb-870d-389ee22d6d36"),
                            Date = "2025-05-18",
                            DoctorId = new Guid("f8917698-59b1-43e8-9de0-3fd3dd455007"),
                            PatientId = "e42df920-2feb-4b70-b9b1-a8c0f5b8c4c3",
                            State = "Scheduled",
                            Time = "14:00 AM"
                        },
                        new
                        {
                            Id = new Guid("6a88e368-27c9-42d3-b601-600340257124"),
                            Date = "2025-05-19",
                            DoctorId = new Guid("0d1c32fd-ceaf-46e4-8329-40f2e6dfcd63"),
                            PatientId = "ce1afefd-f4a4-4b5b-84d8-5cb08a2209e6",
                            State = "Scheduled",
                            Time = "15:00 AM"
                        },
                        new
                        {
                            Id = new Guid("3df8f32a-4a7b-4eba-8e5e-d33179839892"),
                            Date = "2025-05-20",
                            DoctorId = new Guid("2db6b0b6-93da-40d3-9b46-19db0a6bfec8"),
                            PatientId = "0953a478-d12a-4d6c-88ae-1cc028476e90",
                            State = "Scheduled",
                            Time = "16:00 AM"
                        });
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a951df2d-8904-4310-a2c0-7013426b72d8"),
                            Price = 101.0,
                            Specialty = "Specialty 1",
                            UserId = "c91183da-6852-42ee-95e3-1451691f55b6"
                        },
                        new
                        {
                            Id = new Guid("f48df05f-d700-4389-8d67-bdf0cc1d89fa"),
                            Price = 102.0,
                            Specialty = "Specialty 2",
                            UserId = "715e1969-810d-4f15-83e3-b0ec15214e9c"
                        },
                        new
                        {
                            Id = new Guid("d123062f-c0b2-4cae-a85c-21553d20079a"),
                            Price = 103.0,
                            Specialty = "Specialty 3",
                            UserId = "d322c03d-54c5-44ab-a819-d573f00a3682"
                        },
                        new
                        {
                            Id = new Guid("e3542f97-fe03-44c6-a855-92ebe016718c"),
                            Price = 104.0,
                            Specialty = "Specialty 4",
                            UserId = "6ff2fe12-5c7b-4a3d-863c-3a27efc825cc"
                        },
                        new
                        {
                            Id = new Guid("957d2881-7e24-407a-bb14-62e29d213749"),
                            Price = 105.0,
                            Specialty = "Specialty 5",
                            UserId = "23f180b7-6e01-4177-8da7-e984c2eeb05c"
                        },
                        new
                        {
                            Id = new Guid("7bd5f392-df1a-4793-abe5-d0ec40ad0a15"),
                            Price = 106.0,
                            Specialty = "Specialty 6",
                            UserId = "b357db39-e45a-4322-af6c-663b6fdeb682"
                        },
                        new
                        {
                            Id = new Guid("8a8b6077-904d-422d-bc21-d1df2a2cdbe5"),
                            Price = 107.0,
                            Specialty = "Specialty 7",
                            UserId = "c95b81b9-7317-4b77-99ac-71a9603f519e"
                        },
                        new
                        {
                            Id = new Guid("a1eafc54-7b06-4e28-a3b1-8769ab6a2d24"),
                            Price = 108.0,
                            Specialty = "Specialty 8",
                            UserId = "3515917f-11bd-4456-8c8c-e7d0f93d64c8"
                        },
                        new
                        {
                            Id = new Guid("0b18971d-f8b1-4bcb-a0db-cfafc16bcc5f"),
                            Price = 109.0,
                            Specialty = "Specialty 9",
                            UserId = "ba22c1a8-7427-4e4a-8485-40e3e864f4c7"
                        },
                        new
                        {
                            Id = new Guid("5ebfd291-b401-401f-b151-751435847e14"),
                            Price = 110.0,
                            Specialty = "Specialty 10",
                            UserId = "9c43b17c-e807-4470-b735-b96e9c7b898a"
                        },
                        new
                        {
                            Id = new Guid("7f0d600a-ca4d-4245-86ef-2f5ce11f1837"),
                            Price = 111.0,
                            Specialty = "Specialty 11",
                            UserId = "50af4672-16ea-4778-b9e3-369f9ad99347"
                        },
                        new
                        {
                            Id = new Guid("c1884f2a-a51b-4ffe-98fd-fad5f18e43bb"),
                            Price = 112.0,
                            Specialty = "Specialty 12",
                            UserId = "9d88e4f0-af96-4294-afd4-f142391b6bb4"
                        },
                        new
                        {
                            Id = new Guid("9e92ed51-7479-47ff-87a7-6ec378eb4ecd"),
                            Price = 113.0,
                            Specialty = "Specialty 13",
                            UserId = "77470fec-c97f-40d8-bb5d-7b224ec41f27"
                        },
                        new
                        {
                            Id = new Guid("d0ac692b-9f0f-4216-91fd-ad837b015339"),
                            Price = 114.0,
                            Specialty = "Specialty 14",
                            UserId = "dcc7f127-732d-4a36-acd0-91c8b501f463"
                        },
                        new
                        {
                            Id = new Guid("21a48de7-3cc5-4371-9bd9-ae585b771b28"),
                            Price = 115.0,
                            Specialty = "Specialty 15",
                            UserId = "7f6cc616-f7db-4555-a971-e988f21653d1"
                        },
                        new
                        {
                            Id = new Guid("3c35065c-c285-4a7c-8a64-78d9a68b981d"),
                            Price = 116.0,
                            Specialty = "Specialty 16",
                            UserId = "892400bc-4c96-4e10-aad5-fc1bbc967e69"
                        },
                        new
                        {
                            Id = new Guid("6d04d0c3-5322-4207-9297-1418ad6384fb"),
                            Price = 117.0,
                            Specialty = "Specialty 17",
                            UserId = "c30f0568-f115-4afe-838b-89ce7f03bcb9"
                        },
                        new
                        {
                            Id = new Guid("f8917698-59b1-43e8-9de0-3fd3dd455007"),
                            Price = 118.0,
                            Specialty = "Specialty 18",
                            UserId = "2732ee84-e1b9-4940-a928-0e7a8a4c2fcf"
                        },
                        new
                        {
                            Id = new Guid("0d1c32fd-ceaf-46e4-8329-40f2e6dfcd63"),
                            Price = 119.0,
                            Specialty = "Specialty 19",
                            UserId = "40fb1538-357f-4815-b255-f5cfd8cad5cc"
                        },
                        new
                        {
                            Id = new Guid("2db6b0b6-93da-40d3-9b46-19db0a6bfec8"),
                            Price = 120.0,
                            Specialty = "Specialty 20",
                            UserId = "279e4bfc-9f06-4d8e-954a-62f6e64a53b8"
                        });
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.FileImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("FileLength")
                        .HasColumnType("float");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PrescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId")
                        .IsUnique()
                        .HasFilter("[DoctorId] IS NOT NULL");

                    b.HasIndex("PrescriptionId")
                        .IsUnique()
                        .HasFilter("[PrescriptionId] IS NOT NULL");

                    b.ToTable("FileImages");
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modification_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("acb0cb88-e6c3-4393-b0e9-4889fb18c1e5"),
                            AppointmentId = new Guid("d590a5c5-d2e0-4231-ad0f-460e214ef2c9"),
                            Description = "Prescription for appointment 1",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("d3b95a8f-89d5-4898-8287-46963783f295"),
                            AppointmentId = new Guid("ac6bd8c4-5e2e-4512-96eb-c14970762902"),
                            Description = "Prescription for appointment 2",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("619e0fa6-5198-4ca3-9960-9fb20aa7fa0a"),
                            AppointmentId = new Guid("2db9da4e-7b06-44da-b556-358715db152e"),
                            Description = "Prescription for appointment 3",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("83c5a062-e198-4cc8-ac3b-e1d1d91c0ec8"),
                            AppointmentId = new Guid("856991e9-6007-4ad7-9083-fea6bc2e1938"),
                            Description = "Prescription for appointment 4",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("b708ca62-d606-4691-add5-036f2705b683"),
                            AppointmentId = new Guid("11e10896-e187-4d5d-aef8-99d7c4a9a72d"),
                            Description = "Prescription for appointment 5",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("b1eb5284-b7c1-456b-831e-ce188adf1f8f"),
                            AppointmentId = new Guid("9be8ef20-91e3-442e-a0cb-916c9f12de2d"),
                            Description = "Prescription for appointment 6",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("3da0668e-c778-43a5-bd40-daab0fbc9c82"),
                            AppointmentId = new Guid("1ec1c562-d22b-4f8f-83a4-9197570161f1"),
                            Description = "Prescription for appointment 7",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("09759f97-b982-45cf-bec1-07ce1c13be81"),
                            AppointmentId = new Guid("b50b2eb6-583c-4929-a16f-d2cbca66111e"),
                            Description = "Prescription for appointment 8",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("d56392d2-8540-4b12-9f50-0b0054e9fd86"),
                            AppointmentId = new Guid("f982d49b-bd29-4954-abc3-726a85d1b345"),
                            Description = "Prescription for appointment 9",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("f49a693d-5ec5-4005-a448-17c45319b1be"),
                            AppointmentId = new Guid("e78454f6-23aa-44cd-8c7e-14a8b3e60d50"),
                            Description = "Prescription for appointment 10",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("a9e1dc53-3c2d-44ba-9e3d-d8246b893321"),
                            AppointmentId = new Guid("61c6df03-612f-4ba3-a0ff-0257828d8e78"),
                            Description = "Prescription for appointment 11",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("ff232b02-2d34-4384-af3e-cec6ff22e8e5"),
                            AppointmentId = new Guid("e5055c43-fb32-4f8d-951a-834ceab1494e"),
                            Description = "Prescription for appointment 12",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("d393d504-3ffe-42bd-9c02-e502ec713f5d"),
                            AppointmentId = new Guid("2a97ac11-a908-4057-95f3-7d1a76866bea"),
                            Description = "Prescription for appointment 13",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("994e25f3-5760-42bc-802a-5a34e71974ac"),
                            AppointmentId = new Guid("07c82a99-37f1-4082-81a3-eff1d4038816"),
                            Description = "Prescription for appointment 14",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("69c777f8-4ae2-4dd4-9258-a8f95f05b09d"),
                            AppointmentId = new Guid("1cd0a6cf-ed55-40f3-a647-7c301fa535b4"),
                            Description = "Prescription for appointment 15",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("243983fb-f07f-4a47-86a2-f9eb175f20e3"),
                            AppointmentId = new Guid("5a4a9cfd-dcb3-4589-8625-dee975450c88"),
                            Description = "Prescription for appointment 16",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("8a3460af-a5f7-4a9c-98d6-9e93514eff8f"),
                            AppointmentId = new Guid("4fa0c945-6a49-41c6-9616-7b7f63f647b9"),
                            Description = "Prescription for appointment 17",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("6dddcfb4-21f7-41b5-886c-420ae40f5f6a"),
                            AppointmentId = new Guid("793688c9-5932-46cb-870d-389ee22d6d36"),
                            Description = "Prescription for appointment 18",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("5f194995-d744-43f4-a2b6-680dacdcfc5b"),
                            AppointmentId = new Guid("6a88e368-27c9-42d3-b601-600340257124"),
                            Description = "Prescription for appointment 19",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("d08e628c-54b0-448c-bae5-0258abd0a753"),
                            AppointmentId = new Guid("3df8f32a-4a7b-4eba-8e5e-d33179839892"),
                            Description = "Prescription for appointment 20",
                            Modification_date = "2025-05-07"
                        });
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.UserApplication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4336e0d3-0e62-48b3-81a6-53dff6c072a5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cc8e338f-0b23-4aa7-8f88-41f3f5bdb634",
                            Email = "admin1@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN1@CLINIC.COM",
                            NormalizedUserName = "ADMIN1@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDlrTGCk1g9+HbT1gKz/kBfIEiG6/vccn1dZus4kAl8gMw0PbSLXEna8GxlQ+M7CBQ==",
                            PhoneNumber = "01000000001",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "16fb9c92-0bbf-4fa1-a15b-774fa377f8c3",
                            TwoFactorEnabled = false,
                            UserName = "admin1@clinic.com"
                        },
                        new
                        {
                            Id = "b2cb952a-14b7-4bee-9f42-77601734bbc4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2e309c95-5d6f-43e6-b6f6-1cc562732e40",
                            Email = "admin2@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN2@CLINIC.COM",
                            NormalizedUserName = "ADMIN2@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMisZOI5rdqX6l9/kn2/hJKNgKRfS7JR7cA2M5dMXHNp2reDxjhkZ+0+OSysV1HkYw==",
                            PhoneNumber = "01000000002",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "a461c5ad-7463-4383-8024-1a9c19fe48f8",
                            TwoFactorEnabled = false,
                            UserName = "admin2@clinic.com"
                        },
                        new
                        {
                            Id = "1b0c027e-0fe0-471c-94c0-a4872f1edaa8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5e35c9c1-1404-4bad-92a4-38cdcb0a5255",
                            Email = "admin3@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN3@CLINIC.COM",
                            NormalizedUserName = "ADMIN3@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBp5qSjnZ96g2kLCXoxSznswsyG9lBnw3mSxqPMtXvqfCthVfZIZZC64lrJZ6NXlfA==",
                            PhoneNumber = "01000000003",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "34d15210-af53-4dff-8a68-c4b51662d26f",
                            TwoFactorEnabled = false,
                            UserName = "admin3@clinic.com"
                        },
                        new
                        {
                            Id = "887c3565-09c4-4d6b-b594-0504523f0430",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d518d0b5-aaf4-4b03-8c67-12640691ec20",
                            Email = "admin4@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN4@CLINIC.COM",
                            NormalizedUserName = "ADMIN4@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELabk28UaJi+R34XDELKOcMg6+R3ik+6kGrVPBt5WJ1GFgdoDoAmy+mwdP7dr/cW+g==",
                            PhoneNumber = "01000000004",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "e66e2bf1-3044-46a8-86da-506c11125b80",
                            TwoFactorEnabled = false,
                            UserName = "admin4@clinic.com"
                        },
                        new
                        {
                            Id = "01fa0d97-457b-41cb-9298-cb8620e5ca9f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "68669fb7-bc92-4d55-b30a-952567db185f",
                            Email = "admin5@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN5@CLINIC.COM",
                            NormalizedUserName = "ADMIN5@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDtcro994GBbhefgC628xZkrX3fjsZZTI0HgCW6GfXOZWYz55bYD+w9u876JpbgL+Q==",
                            PhoneNumber = "01000000005",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1f969942-4306-47f3-943f-4da441373490",
                            TwoFactorEnabled = false,
                            UserName = "admin5@clinic.com"
                        },
                        new
                        {
                            Id = "557bbb5c-6368-4ad6-a3bc-e38948632b88",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9dea44b0-1f70-4c12-96f5-5a541729f188",
                            Email = "patient1@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT1@CLINIC.COM",
                            NormalizedUserName = "PATIENT1@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKKTbuD3VmtUQWAyhLJ5R76UiuwE6wuTyy5HZfPkBztpE2PTTVlqYLmTbroE293cZg==",
                            PhoneNumber = "01000000001",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "f3cb4e33-2b65-4fe7-8fe1-05f350b90064",
                            TwoFactorEnabled = false,
                            UserName = "patient1@clinic.com"
                        },
                        new
                        {
                            Id = "fbaa04e4-ebb4-4cf2-a860-2bf13cd67895",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6af91653-3bfe-4ca2-8082-51273f720059",
                            Email = "patient2@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT2@CLINIC.COM",
                            NormalizedUserName = "PATIENT2@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKfh3Uw7/tCuYLEgD9/s/A6z2+5N7l3/oILh9m6JjHm4/zAMu3GMQ3DUJRKrkOBygw==",
                            PhoneNumber = "01000000002",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "ccfc1df8-24b6-42b8-b0b5-c07b0d51a3df",
                            TwoFactorEnabled = false,
                            UserName = "patient2@clinic.com"
                        },
                        new
                        {
                            Id = "a63e6d2f-c623-4681-88f7-83c9c4649269",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1d05f13f-6c97-44a6-bc08-a85d51103187",
                            Email = "patient3@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT3@CLINIC.COM",
                            NormalizedUserName = "PATIENT3@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHp+jplVkwJmq1bXTnf/MLXbP2epNdNDqsmWga+3ME0dBdq7Nz8nWrhj4sPR/vU9Qw==",
                            PhoneNumber = "01000000003",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "bd41ccbe-34c4-4256-9b89-cf003a0238bf",
                            TwoFactorEnabled = false,
                            UserName = "patient3@clinic.com"
                        },
                        new
                        {
                            Id = "5164ed58-4b9e-47cf-8ec3-096394761f2a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c3833db9-7d3d-4901-80e8-52a0d7559f09",
                            Email = "patient4@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT4@CLINIC.COM",
                            NormalizedUserName = "PATIENT4@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIifx1MjVTtknSuZ41rvig3HD4JIOtkE+tjiiaHI230294HL4jAjHRJnivOSLirjhw==",
                            PhoneNumber = "01000000004",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "cfe16693-55cc-46a9-963e-4e2af93fe286",
                            TwoFactorEnabled = false,
                            UserName = "patient4@clinic.com"
                        },
                        new
                        {
                            Id = "551b9e2a-a76e-4643-a701-aef28baa6b0d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a176da50-d92b-469c-be95-9f7328f449c7",
                            Email = "patient5@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT5@CLINIC.COM",
                            NormalizedUserName = "PATIENT5@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAAOdwWNG36dfOGah7gO64XLGrvKk6LGyX/D3CezMDJ2er3E1Tk0Hq19ucnLwmuR0w==",
                            PhoneNumber = "01000000005",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1c012508-a62a-4f7c-bfc1-4204024c668e",
                            TwoFactorEnabled = false,
                            UserName = "patient5@clinic.com"
                        },
                        new
                        {
                            Id = "8bef09fd-e7e2-4146-aa8f-2a632b8b9d2d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e51425a8-1063-4224-8382-5284c411afaa",
                            Email = "patient6@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT6@CLINIC.COM",
                            NormalizedUserName = "PATIENT6@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEH1JNkfYlMomHrGFlYMo780YHwDgJlfcTaYWq49tl9rdLZlcHWveDu3N98gEjtpD+g==",
                            PhoneNumber = "01000000006",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "bb02fab8-bbe2-4e0a-8ea5-adba3dcd4598",
                            TwoFactorEnabled = false,
                            UserName = "patient6@clinic.com"
                        },
                        new
                        {
                            Id = "a89af95f-b24a-40fe-addf-d34f31925755",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "70da2794-3670-4139-ba66-d710b6ca3317",
                            Email = "patient7@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT7@CLINIC.COM",
                            NormalizedUserName = "PATIENT7@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFhgWGd98OPo/bcC+RVt0H/lv51C8pG6aldSgsiNk1y2+4Xrkn7vE5BR2YSjiTBzEw==",
                            PhoneNumber = "01000000007",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1b03b59d-0d7d-4993-8b60-b0f05e172b1e",
                            TwoFactorEnabled = false,
                            UserName = "patient7@clinic.com"
                        },
                        new
                        {
                            Id = "ef82c308-ada0-4767-ae06-d7be1d85be1f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c8d9a622-0c4e-400b-b39a-2729df6c4307",
                            Email = "patient8@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT8@CLINIC.COM",
                            NormalizedUserName = "PATIENT8@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAED4vh0I6+7gCKSS5DGHEpXnRPplOrJxXVwQmK7pRjjYagsMgMKQsrMP0NnV1OCVyJA==",
                            PhoneNumber = "01000000008",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "04fa2290-3feb-448a-8653-b8b2348ccc83",
                            TwoFactorEnabled = false,
                            UserName = "patient8@clinic.com"
                        },
                        new
                        {
                            Id = "fc4b8c77-6015-48a9-be61-3485498c45d6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ed2ef9b3-1835-499c-a90b-b036738d853b",
                            Email = "patient9@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT9@CLINIC.COM",
                            NormalizedUserName = "PATIENT9@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHB5FkHN91vtZZc2saiYGqtOYXLjdLQzr9AMvIw5skLQanwroD04CU8zhUUmzU6chg==",
                            PhoneNumber = "01000000009",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "93d58865-adf0-442a-9386-4b0d350d9685",
                            TwoFactorEnabled = false,
                            UserName = "patient9@clinic.com"
                        },
                        new
                        {
                            Id = "c3208482-a0e6-4090-88c6-aecda7592bbc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "78fad36e-0f70-4069-b264-f66263e83070",
                            Email = "patient10@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT10@CLINIC.COM",
                            NormalizedUserName = "PATIENT10@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMsnesgsUQOTuclAL7OfTJv3pNyPXuu9A/cCBnHL3LZ4pU3i5IfEhM0iKCHyBU7jTw==",
                            PhoneNumber = "01000000010",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "5c904d94-0995-4f32-b39c-e5d4cecf2431",
                            TwoFactorEnabled = false,
                            UserName = "patient10@clinic.com"
                        },
                        new
                        {
                            Id = "d5c31600-3ba1-4907-b72b-4d56ef4f68c6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5a01e9a1-a055-4758-a512-0a0f288f100a",
                            Email = "patient11@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT11@CLINIC.COM",
                            NormalizedUserName = "PATIENT11@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOIWDrOmcVM8FxDArBy1Iv+eKEceUwNCRMSIPcFFGBWqZvV5x4iwqXH7y3xLxb0ikA==",
                            PhoneNumber = "01000000011",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "f45eb4f9-afcb-4cd7-a76f-d53912bf93e4",
                            TwoFactorEnabled = false,
                            UserName = "patient11@clinic.com"
                        },
                        new
                        {
                            Id = "f3f8c375-0e9f-44d2-9023-8eab65ea9d85",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ab618956-6f35-4f78-aa7a-495e5eeb192f",
                            Email = "patient12@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT12@CLINIC.COM",
                            NormalizedUserName = "PATIENT12@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAAvtWNZn9XKR3/eCigdkOuYF6XUvSgLR/1Do30oJ1creeM3b6laTUh4iYhaPTVSRg==",
                            PhoneNumber = "01000000012",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "de0e75f3-d642-47b8-834f-016eaf7274af",
                            TwoFactorEnabled = false,
                            UserName = "patient12@clinic.com"
                        },
                        new
                        {
                            Id = "e42df920-2feb-4b70-b9b1-a8c0f5b8c4c3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "34764e5f-288b-4c81-a882-0ce0d8568cd0",
                            Email = "patient13@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT13@CLINIC.COM",
                            NormalizedUserName = "PATIENT13@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMmKniOtXnMskcJs7DzA4KD8apkubgesokpRDESrma6A7crOGNdhUrbvbSgXS66wsg==",
                            PhoneNumber = "01000000013",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "c1f79fba-aeb2-4fb8-94c7-e7c41ac03336",
                            TwoFactorEnabled = false,
                            UserName = "patient13@clinic.com"
                        },
                        new
                        {
                            Id = "ce1afefd-f4a4-4b5b-84d8-5cb08a2209e6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "183344ca-4366-4460-a184-9ca0266a40d6",
                            Email = "patient14@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT14@CLINIC.COM",
                            NormalizedUserName = "PATIENT14@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEK/lJTULuz1zStlN6R3531E3/jioWOr/fuxOag1z4xFTVqDGigb9JjSxxeF3+NWA7A==",
                            PhoneNumber = "01000000014",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "b26f6cb5-2d57-4d5d-a4f6-0cf4b22a4c03",
                            TwoFactorEnabled = false,
                            UserName = "patient14@clinic.com"
                        },
                        new
                        {
                            Id = "0953a478-d12a-4d6c-88ae-1cc028476e90",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "281a707e-3260-4732-a54f-fa40acc71669",
                            Email = "patient15@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT15@CLINIC.COM",
                            NormalizedUserName = "PATIENT15@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECKzIZiTHSz0uOeUqmRIiuiND5X1rUhBZ+TOTqJsYsargYuovvV82ql1A8Xz58NH5g==",
                            PhoneNumber = "01000000015",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "9550a96d-c31e-46b3-adbb-cef07da35360",
                            TwoFactorEnabled = false,
                            UserName = "patient15@clinic.com"
                        },
                        new
                        {
                            Id = "04a088b3-76d5-49f5-9a15-9c8528fe83a3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "478f4777-0804-41f9-b43f-38c91d3951cf",
                            Email = "patient16@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT16@CLINIC.COM",
                            NormalizedUserName = "PATIENT16@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOYo8BoGk5zX5sip00uWr/2DwY9vM3tUkhx3+bBmaT3MBe3BzMOi6fDkHt82AvlCcA==",
                            PhoneNumber = "01000000016",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "6630e13f-6e8c-413f-ac72-199b5cf8028c",
                            TwoFactorEnabled = false,
                            UserName = "patient16@clinic.com"
                        },
                        new
                        {
                            Id = "daddd432-bf38-401f-8e3e-b142a35bed05",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "262f1c03-a3b0-4bce-9147-19183084b486",
                            Email = "patient17@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT17@CLINIC.COM",
                            NormalizedUserName = "PATIENT17@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKmt83tdoJlFVV4AIyZgVcrZPcpCf21ZOMx3eVNCEeDbfHVHEdQ47qFLWurwmAa8yw==",
                            PhoneNumber = "01000000017",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "a8ac3676-e18a-4cf5-930d-0fbd58f9fca6",
                            TwoFactorEnabled = false,
                            UserName = "patient17@clinic.com"
                        },
                        new
                        {
                            Id = "bfadb927-0335-4f68-8897-2148a1b4acc5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1dff7ef1-430c-4ade-9580-56f04e6c5cc7",
                            Email = "patient18@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT18@CLINIC.COM",
                            NormalizedUserName = "PATIENT18@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPURJEBsp7SswZeNk3c8R8o4q7HT12cbsFtpapn7KGe47JqmiWptPbSfiLTCdPm71Q==",
                            PhoneNumber = "01000000018",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "58f47a00-d3f0-4295-b892-68f2635619f3",
                            TwoFactorEnabled = false,
                            UserName = "patient18@clinic.com"
                        },
                        new
                        {
                            Id = "5f82ce10-5227-4446-a7f9-43b35f4b2fa5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1c0f00a2-d812-42ea-ae0a-dccf1684c8a6",
                            Email = "patient19@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT19@CLINIC.COM",
                            NormalizedUserName = "PATIENT19@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPjb+LeXO91gfAA9JciHrAOYfBKxkysxpmEWBdSMThSrvP3sl5eBgZnXl/A0fT2nRw==",
                            PhoneNumber = "01000000019",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "79deac0d-8139-409b-859c-8b5151ba4a2a",
                            TwoFactorEnabled = false,
                            UserName = "patient19@clinic.com"
                        },
                        new
                        {
                            Id = "da49b029-1380-4edc-9eb6-718d56584d11",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8fd328c4-cd07-4629-aa24-9d974aa95b2e",
                            Email = "patient20@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT20@CLINIC.COM",
                            NormalizedUserName = "PATIENT20@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPAhnB1u+QI53j7NHGuwvzZChbkn4BrJ2qgLw2ol3HDPI9P5l7ByE5t2i3C7JKjeBw==",
                            PhoneNumber = "01000000020",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "95aaa568-4ddb-47b9-bf28-d607ed52adc8",
                            TwoFactorEnabled = false,
                            UserName = "patient20@clinic.com"
                        },
                        new
                        {
                            Id = "c91183da-6852-42ee-95e3-1451691f55b6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6f0dad6b-cc58-490e-8578-d468681d2150",
                            Email = "doctor1@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR1@CLINIC.COM",
                            NormalizedUserName = "DOCTOR1@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECL6OhPtbMy5gCpQnM0JC1q++fh0IV0uifvJ/pgR2y7zs3dopKUaRPNd6kcADsbisQ==",
                            PhoneNumber = "01100000001",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "3b0d592c-3dc9-4633-ae54-7e79f4c10bc9",
                            TwoFactorEnabled = false,
                            UserName = "doctor1@clinic.com"
                        },
                        new
                        {
                            Id = "715e1969-810d-4f15-83e3-b0ec15214e9c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2080e7aa-ea9b-421d-9d38-43bdfe7cf3b1",
                            Email = "doctor2@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR2@CLINIC.COM",
                            NormalizedUserName = "DOCTOR2@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKetXsV7WmJ3yLHu+NKDrNDFBBrmNkeTAQbj/t3P7EIAzgrxUFk00tMjtk5kvbpLZA==",
                            PhoneNumber = "01100000002",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "9de6ddcb-a88b-4b3f-ac81-16db3445b5e1",
                            TwoFactorEnabled = false,
                            UserName = "doctor2@clinic.com"
                        },
                        new
                        {
                            Id = "d322c03d-54c5-44ab-a819-d573f00a3682",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "64c437b8-ae66-42e2-98e0-6b858dc2390d",
                            Email = "doctor3@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR3@CLINIC.COM",
                            NormalizedUserName = "DOCTOR3@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEET/li8DKZqAmk6ePWwAGNLzH5XQZjvEp/FWeUhFcomeX9eY2nRBesyQLlX5zKEB1w==",
                            PhoneNumber = "01100000003",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "b6795522-452a-47d9-931e-aa78e7d5999d",
                            TwoFactorEnabled = false,
                            UserName = "doctor3@clinic.com"
                        },
                        new
                        {
                            Id = "6ff2fe12-5c7b-4a3d-863c-3a27efc825cc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "af1adb93-ea9f-405e-8082-db2257475cb0",
                            Email = "doctor4@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR4@CLINIC.COM",
                            NormalizedUserName = "DOCTOR4@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEB0Ln9qSve+m2pjzIZMKNtHoR9jc5tmxRNr4izqboU2drSi4Th0/iyTt5f6Gbw833w==",
                            PhoneNumber = "01100000004",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "88edc806-3de3-4173-a36b-fb280933a4fc",
                            TwoFactorEnabled = false,
                            UserName = "doctor4@clinic.com"
                        },
                        new
                        {
                            Id = "23f180b7-6e01-4177-8da7-e984c2eeb05c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f247f275-1814-41e1-a9cc-acbf9f8a9d1a",
                            Email = "doctor5@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR5@CLINIC.COM",
                            NormalizedUserName = "DOCTOR5@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEC2sBalmpzg8g5U6suV1JU+aNqjkTboQmPhJ6xNL6NHfpIuYis5lx+k1mT3ZY/xxnQ==",
                            PhoneNumber = "01100000005",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "ac9ce9a4-81e1-4527-a88a-6037d95be54f",
                            TwoFactorEnabled = false,
                            UserName = "doctor5@clinic.com"
                        },
                        new
                        {
                            Id = "b357db39-e45a-4322-af6c-663b6fdeb682",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "68ee59b0-d809-4bea-a9da-83d16711f5b7",
                            Email = "doctor6@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR6@CLINIC.COM",
                            NormalizedUserName = "DOCTOR6@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENFOl5m9Y+aO6Gc+oOggP1m47mgWrxe3+qQbLvwJpck3lJjZc0aw0Mvrq8FSYAjLuA==",
                            PhoneNumber = "01100000006",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "9086248d-4796-4653-a8a1-eef2f1d52fb7",
                            TwoFactorEnabled = false,
                            UserName = "doctor6@clinic.com"
                        },
                        new
                        {
                            Id = "c95b81b9-7317-4b77-99ac-71a9603f519e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e0ea6941-42d1-4b06-9566-70ccd8152a11",
                            Email = "doctor7@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR7@CLINIC.COM",
                            NormalizedUserName = "DOCTOR7@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMFdFJOPbnNxubC9UaMHG+bV10CT1wu3yAZIdVoAAB6J5sEuy73UDZ+608LiweXbag==",
                            PhoneNumber = "01100000007",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "c8ded6b2-26fa-4e4c-9d3f-97ea555abfe8",
                            TwoFactorEnabled = false,
                            UserName = "doctor7@clinic.com"
                        },
                        new
                        {
                            Id = "3515917f-11bd-4456-8c8c-e7d0f93d64c8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "171413f2-5978-41e8-90c8-97f6a07bfd44",
                            Email = "doctor8@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR8@CLINIC.COM",
                            NormalizedUserName = "DOCTOR8@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEL5oXU1SsqZCNSCqC58gZp3WLVtKOabjnsxxgxgBhBMvbEMnKs/s5W3fYak7byJDlg==",
                            PhoneNumber = "01100000008",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "67c927e5-76e7-4819-a052-f303fce71e3b",
                            TwoFactorEnabled = false,
                            UserName = "doctor8@clinic.com"
                        },
                        new
                        {
                            Id = "ba22c1a8-7427-4e4a-8485-40e3e864f4c7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5358364a-6a2b-410b-84d1-89c2d9267ed3",
                            Email = "doctor9@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR9@CLINIC.COM",
                            NormalizedUserName = "DOCTOR9@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEK3+hIAtqrGjiJUNPMGPKJ0zovG64+4fX0SXf8vqh+sYVYMFkeXznpIMs6IqOCfE7Q==",
                            PhoneNumber = "01100000009",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "e25daa9c-6a21-4477-a9ff-753c9317f87d",
                            TwoFactorEnabled = false,
                            UserName = "doctor9@clinic.com"
                        },
                        new
                        {
                            Id = "9c43b17c-e807-4470-b735-b96e9c7b898a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "36e79f40-168f-4329-9330-277788f0f723",
                            Email = "doctor10@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR10@CLINIC.COM",
                            NormalizedUserName = "DOCTOR10@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMmddVDGRdXNeM/wVyNYphT1DtAtcEoo1922D8YV7w99gZgMGm7W/c6a+1UoXOl2HA==",
                            PhoneNumber = "01100000010",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "8586dc6e-ee5f-4af6-bd2c-40b36a7618e6",
                            TwoFactorEnabled = false,
                            UserName = "doctor10@clinic.com"
                        },
                        new
                        {
                            Id = "50af4672-16ea-4778-b9e3-369f9ad99347",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6e2e4e4b-c6a4-46a5-853a-4cc2be6132c7",
                            Email = "doctor11@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR11@CLINIC.COM",
                            NormalizedUserName = "DOCTOR11@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHQmvV7l+zqMV8u3YFVyK7wpHl6YvPjRTanlGxqa6WsjdDe79rAGm3Xu6zbtFUqTbQ==",
                            PhoneNumber = "01100000011",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "63fde46f-01bb-4011-91a3-685037796d01",
                            TwoFactorEnabled = false,
                            UserName = "doctor11@clinic.com"
                        },
                        new
                        {
                            Id = "9d88e4f0-af96-4294-afd4-f142391b6bb4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "afdff8c9-0d23-438a-8e27-0b27566db166",
                            Email = "doctor12@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR12@CLINIC.COM",
                            NormalizedUserName = "DOCTOR12@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELlZizxhiGZyWWZQBQ49bU6b7q8b8hysahcNcQ4XpPlQWTUE3rQt6lje0Zmw7kr9tw==",
                            PhoneNumber = "01100000012",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1f478d95-670c-4b32-b1cb-ad37e63378fc",
                            TwoFactorEnabled = false,
                            UserName = "doctor12@clinic.com"
                        },
                        new
                        {
                            Id = "77470fec-c97f-40d8-bb5d-7b224ec41f27",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e4a40df6-edcf-4990-bc79-80374dabc2e2",
                            Email = "doctor13@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR13@CLINIC.COM",
                            NormalizedUserName = "DOCTOR13@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPBTdUqCC/OvTu2rIzHF9xgErTZMfqML9CPQRMmZTJdy6S0NGYON8kExJrhpOviZDA==",
                            PhoneNumber = "01100000013",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "056ddc46-3b3c-422f-8603-561f14d15457",
                            TwoFactorEnabled = false,
                            UserName = "doctor13@clinic.com"
                        },
                        new
                        {
                            Id = "dcc7f127-732d-4a36-acd0-91c8b501f463",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ad1daafc-6ef9-44ea-99e9-9fb25740eba6",
                            Email = "doctor14@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR14@CLINIC.COM",
                            NormalizedUserName = "DOCTOR14@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEISUBj1qAa33vW85O7zrfrxmrFaZZMgBYHg5L34ZGy4HUc/BSyF2oUsF4YJG/m6qeA==",
                            PhoneNumber = "01100000014",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "bfe9940d-9e51-4f4b-ba00-203fc53de00a",
                            TwoFactorEnabled = false,
                            UserName = "doctor14@clinic.com"
                        },
                        new
                        {
                            Id = "7f6cc616-f7db-4555-a971-e988f21653d1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "856d92ee-7cb3-4ebc-9d3b-bead7bf1d80a",
                            Email = "doctor15@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR15@CLINIC.COM",
                            NormalizedUserName = "DOCTOR15@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJH4K58O4i1h++N9D2Zaj20T5XpztXTNYnucBMu7OcwkWM0hG0VMBwx7z5BEQ9xvAg==",
                            PhoneNumber = "01100000015",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1e388de4-d7af-47cd-bf8f-0a7711ff0733",
                            TwoFactorEnabled = false,
                            UserName = "doctor15@clinic.com"
                        },
                        new
                        {
                            Id = "892400bc-4c96-4e10-aad5-fc1bbc967e69",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7c6d6808-9b02-4c07-8c9c-48474700e185",
                            Email = "doctor16@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR16@CLINIC.COM",
                            NormalizedUserName = "DOCTOR16@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGIsLB8t63kuHm35jQJqEfiNgqzvcu9/E1VtxyI/06UTGXNPBSTK7jfVIEKwEJp+BA==",
                            PhoneNumber = "01100000016",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "bca55188-4f14-4211-a649-12ca62ecebed",
                            TwoFactorEnabled = false,
                            UserName = "doctor16@clinic.com"
                        },
                        new
                        {
                            Id = "c30f0568-f115-4afe-838b-89ce7f03bcb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e746165a-3942-4451-a165-9984e08f9fc6",
                            Email = "doctor17@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR17@CLINIC.COM",
                            NormalizedUserName = "DOCTOR17@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPw5dvTrEZajTLH2QVNy0lI6TXAn0PWFoEa/Je+OPYTuqFp9zRooQ5eU72Yg6tUDaQ==",
                            PhoneNumber = "01100000017",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "8035febc-7626-466f-aa8a-76b8dcfe8ba5",
                            TwoFactorEnabled = false,
                            UserName = "doctor17@clinic.com"
                        },
                        new
                        {
                            Id = "2732ee84-e1b9-4940-a928-0e7a8a4c2fcf",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5447b736-1b2c-4c1b-9f8c-54af963ceefa",
                            Email = "doctor18@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR18@CLINIC.COM",
                            NormalizedUserName = "DOCTOR18@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIMojYIeS7ZaGcv2LnF9vtArKqswMxN/NCTQKt15FgW6P3DYV2W4dlB9qHr/YUfw0A==",
                            PhoneNumber = "01100000018",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "f46e7e96-c6de-44d1-9200-c99a8d391012",
                            TwoFactorEnabled = false,
                            UserName = "doctor18@clinic.com"
                        },
                        new
                        {
                            Id = "40fb1538-357f-4815-b255-f5cfd8cad5cc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ee4186ce-b006-4587-aa75-89b1bd08b722",
                            Email = "doctor19@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR19@CLINIC.COM",
                            NormalizedUserName = "DOCTOR19@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEjNptX7N0zkdl1SJPC1b9HIg/O1n8iPCXzEEuDoIWcqjBszVLJcD26158Al/EbhLA==",
                            PhoneNumber = "01100000019",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "760db880-bb51-430e-bd59-a3d86d2d8af9",
                            TwoFactorEnabled = false,
                            UserName = "doctor19@clinic.com"
                        },
                        new
                        {
                            Id = "279e4bfc-9f06-4d8e-954a-62f6e64a53b8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "54b8c9f8-7bdf-423a-92dc-cec11c72e5cf",
                            Email = "doctor20@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR20@CLINIC.COM",
                            NormalizedUserName = "DOCTOR20@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELalAxe6+wfANkk45XHVdceMhGGewu2osBDpfAqkwBN5+OP9QSoUkMRLTsPLh60qaw==",
                            PhoneNumber = "01100000020",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "3b9ed67c-383f-4aae-86b2-8985f5a75d38",
                            TwoFactorEnabled = false,
                            UserName = "doctor20@clinic.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "675b578c-8739-4b1b-a706-816fb14910bd",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "72235979-4cb2-4bb1-9de9-9e931f98610e",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "4336e0d3-0e62-48b3-81a6-53dff6c072a5",
                            RoleId = "675b578c-8739-4b1b-a706-816fb14910bd"
                        },
                        new
                        {
                            UserId = "b2cb952a-14b7-4bee-9f42-77601734bbc4",
                            RoleId = "675b578c-8739-4b1b-a706-816fb14910bd"
                        },
                        new
                        {
                            UserId = "1b0c027e-0fe0-471c-94c0-a4872f1edaa8",
                            RoleId = "675b578c-8739-4b1b-a706-816fb14910bd"
                        },
                        new
                        {
                            UserId = "887c3565-09c4-4d6b-b594-0504523f0430",
                            RoleId = "675b578c-8739-4b1b-a706-816fb14910bd"
                        },
                        new
                        {
                            UserId = "01fa0d97-457b-41cb-9298-cb8620e5ca9f",
                            RoleId = "675b578c-8739-4b1b-a706-816fb14910bd"
                        },
                        new
                        {
                            UserId = "557bbb5c-6368-4ad6-a3bc-e38948632b88",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "fbaa04e4-ebb4-4cf2-a860-2bf13cd67895",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "a63e6d2f-c623-4681-88f7-83c9c4649269",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "5164ed58-4b9e-47cf-8ec3-096394761f2a",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "551b9e2a-a76e-4643-a701-aef28baa6b0d",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "8bef09fd-e7e2-4146-aa8f-2a632b8b9d2d",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "a89af95f-b24a-40fe-addf-d34f31925755",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "ef82c308-ada0-4767-ae06-d7be1d85be1f",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "fc4b8c77-6015-48a9-be61-3485498c45d6",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "c3208482-a0e6-4090-88c6-aecda7592bbc",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "d5c31600-3ba1-4907-b72b-4d56ef4f68c6",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "f3f8c375-0e9f-44d2-9023-8eab65ea9d85",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "e42df920-2feb-4b70-b9b1-a8c0f5b8c4c3",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "ce1afefd-f4a4-4b5b-84d8-5cb08a2209e6",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "0953a478-d12a-4d6c-88ae-1cc028476e90",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "04a088b3-76d5-49f5-9a15-9c8528fe83a3",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "daddd432-bf38-401f-8e3e-b142a35bed05",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "bfadb927-0335-4f68-8897-2148a1b4acc5",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "5f82ce10-5227-4446-a7f9-43b35f4b2fa5",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "da49b029-1380-4edc-9eb6-718d56584d11",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "c91183da-6852-42ee-95e3-1451691f55b6",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "715e1969-810d-4f15-83e3-b0ec15214e9c",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "d322c03d-54c5-44ab-a819-d573f00a3682",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "6ff2fe12-5c7b-4a3d-863c-3a27efc825cc",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "23f180b7-6e01-4177-8da7-e984c2eeb05c",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "b357db39-e45a-4322-af6c-663b6fdeb682",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "c95b81b9-7317-4b77-99ac-71a9603f519e",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "3515917f-11bd-4456-8c8c-e7d0f93d64c8",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "ba22c1a8-7427-4e4a-8485-40e3e864f4c7",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "9c43b17c-e807-4470-b735-b96e9c7b898a",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "50af4672-16ea-4778-b9e3-369f9ad99347",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "9d88e4f0-af96-4294-afd4-f142391b6bb4",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "77470fec-c97f-40d8-bb5d-7b224ec41f27",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "dcc7f127-732d-4a36-acd0-91c8b501f463",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "7f6cc616-f7db-4555-a971-e988f21653d1",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "892400bc-4c96-4e10-aad5-fc1bbc967e69",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "c30f0568-f115-4afe-838b-89ce7f03bcb9",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "2732ee84-e1b9-4940-a928-0e7a8a4c2fcf",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "40fb1538-357f-4815-b255-f5cfd8cad5cc",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "279e4bfc-9f06-4d8e-954a-62f6e64a53b8",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Appointment", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Doctor", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", "userApplication")
                        .WithOne()
                        .HasForeignKey("ClinicAPI.Models.Domain.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userApplication");
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.FileImage", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.Doctor", "Doctor")
                        .WithOne("FileImage")
                        .HasForeignKey("ClinicAPI.Models.Domain.FileImage", "DoctorId");

                    b.HasOne("ClinicAPI.Models.Domain.Prescription", "Prescription")
                        .WithOne("FileImage")
                        .HasForeignKey("ClinicAPI.Models.Domain.FileImage", "PrescriptionId");

                    b.Navigation("Doctor");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Prescription", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.Appointment", "Appointment")
                        .WithOne("Prescription")
                        .HasForeignKey("ClinicAPI.Models.Domain.Prescription", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Appointment", b =>
                {
                    b.Navigation("Prescription")
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("FileImage")
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Prescription", b =>
                {
                    b.Navigation("FileImage")
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.UserApplication", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
