// <auto-generated />
using System;
using ClinicAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250506201540_SeedRolesAndUsers")]
    partial class SeedRolesAndUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicAPI.Models.Domain.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PatientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e93ead83-0fd9-427e-b76c-f742c2b9bf3b"),
                            Date = "2025-05-01",
                            DoctorId = new Guid("95e93ba9-8feb-449a-9310-10f4f1cfa6ae"),
                            PatientId = "f90968cb-de1f-46a0-a508-0e13fef63922",
                            State = "Scheduled",
                            Time = "9:00 AM"
                        },
                        new
                        {
                            Id = new Guid("2d6a4ecd-51b6-48b7-9f79-ac5ce492402b"),
                            Date = "2025-05-02",
                            DoctorId = new Guid("f8db328e-f29a-4edf-90e2-fa0af9b2f2f7"),
                            PatientId = "ce05714c-0de2-4fd6-afc0-867f4aca74d8",
                            State = "Scheduled",
                            Time = "10:00 AM"
                        },
                        new
                        {
                            Id = new Guid("b053a945-94de-432f-b309-818acfbb0576"),
                            Date = "2025-05-03",
                            DoctorId = new Guid("8eccff74-55a0-41da-b610-3bde51af8e1d"),
                            PatientId = "755a8257-ad4c-44ac-8e69-ae15c27eb1e0",
                            State = "Scheduled",
                            Time = "11:00 AM"
                        },
                        new
                        {
                            Id = new Guid("ff562776-5ecb-49ae-961d-57ccdce8ac3e"),
                            Date = "2025-05-04",
                            DoctorId = new Guid("35a89b32-a9f3-4d8b-b05c-e43f7d3d383d"),
                            PatientId = "9f5a316e-c0f8-417c-93a7-0e8bdf371660",
                            State = "Scheduled",
                            Time = "12:00 AM"
                        },
                        new
                        {
                            Id = new Guid("04623cc9-a4b6-4fe7-9340-8f46df018a61"),
                            Date = "2025-05-05",
                            DoctorId = new Guid("8ec0e9a2-5b1b-472d-bd19-b01af2e2a4b8"),
                            PatientId = "8bb59f45-c04f-49cd-bdb1-67196483be35",
                            State = "Scheduled",
                            Time = "13:00 AM"
                        },
                        new
                        {
                            Id = new Guid("8debbab0-faae-4539-ac70-0055c5edbb53"),
                            Date = "2025-05-06",
                            DoctorId = new Guid("586a05c8-9376-4501-873d-b79f6332874f"),
                            PatientId = "eee26db5-0164-495f-89f2-83ea285db8c0",
                            State = "Scheduled",
                            Time = "14:00 AM"
                        },
                        new
                        {
                            Id = new Guid("083f0240-a7a9-48a5-b180-19ac48bfac03"),
                            Date = "2025-05-07",
                            DoctorId = new Guid("1ee3aa75-f8b2-4d41-9372-a70900e8ac7c"),
                            PatientId = "8ca7d99f-35d7-4651-836c-d9d061a49427",
                            State = "Scheduled",
                            Time = "15:00 AM"
                        },
                        new
                        {
                            Id = new Guid("7a8eebfe-9f72-449b-8047-fb1f1541b37f"),
                            Date = "2025-05-08",
                            DoctorId = new Guid("6ac96d36-36e6-44f2-bbf6-6578898b494d"),
                            PatientId = "a12ab74b-ba32-4056-b607-202472f76ca2",
                            State = "Scheduled",
                            Time = "16:00 AM"
                        },
                        new
                        {
                            Id = new Guid("f716fdb0-5e03-4a7a-8bd5-52c3bd0c60aa"),
                            Date = "2025-05-09",
                            DoctorId = new Guid("da4da8de-4558-4d72-a225-054fabbaa9da"),
                            PatientId = "931c0531-e15c-48e1-8a5c-b30c62eb50f9",
                            State = "Scheduled",
                            Time = "17:00 AM"
                        },
                        new
                        {
                            Id = new Guid("7985db89-7d11-4e96-967f-a1b5c54c419f"),
                            Date = "2025-05-10",
                            DoctorId = new Guid("5aa28e01-644d-498c-b66f-bfc2c720cb88"),
                            PatientId = "6627e77d-6c04-4165-a1a9-8e45915006a3",
                            State = "Scheduled",
                            Time = "18:00 AM"
                        },
                        new
                        {
                            Id = new Guid("c57e79c6-076d-4b96-99f6-7baa3ea75cb0"),
                            Date = "2025-05-11",
                            DoctorId = new Guid("75cb34ef-6a82-4d78-b770-70408334d8fa"),
                            PatientId = "96ec0f2d-d4cb-46c1-a1bf-73900a1592f5",
                            State = "Scheduled",
                            Time = "19:00 AM"
                        },
                        new
                        {
                            Id = new Guid("2c1ff423-e321-44db-8e9a-035797b483f6"),
                            Date = "2025-05-12",
                            DoctorId = new Guid("c4485f07-ece1-410c-af94-321edfde9425"),
                            PatientId = "2ec8090b-edb6-42d2-9109-c8296f933566",
                            State = "Scheduled",
                            Time = "20:00 AM"
                        },
                        new
                        {
                            Id = new Guid("dc91d62a-5663-4cbf-97db-8eee9d47e832"),
                            Date = "2025-05-13",
                            DoctorId = new Guid("d7aad276-d4c1-4bee-b695-4cba94abb37a"),
                            PatientId = "d750d504-86db-4df3-ba0d-f5d2bc2f213b",
                            State = "Scheduled",
                            Time = "9:00 AM"
                        },
                        new
                        {
                            Id = new Guid("148d0b11-06be-4498-b3a1-41b431406969"),
                            Date = "2025-05-14",
                            DoctorId = new Guid("ed39d351-1002-40d0-858c-846c3f2b0764"),
                            PatientId = "d3c97e74-8660-494a-a2af-eaa94baedfe4",
                            State = "Scheduled",
                            Time = "10:00 AM"
                        },
                        new
                        {
                            Id = new Guid("86988fdf-7997-4e00-8ac9-cc538275673b"),
                            Date = "2025-05-15",
                            DoctorId = new Guid("951488a8-30b3-4e3c-9aeb-6c548e5349cb"),
                            PatientId = "023978a1-0aad-43dc-8b37-b9bfa1c69d64",
                            State = "Scheduled",
                            Time = "11:00 AM"
                        },
                        new
                        {
                            Id = new Guid("64e03248-4402-4bed-a7ca-af53dd219328"),
                            Date = "2025-05-16",
                            DoctorId = new Guid("67457fae-0354-4697-a68f-a3c996454db8"),
                            PatientId = "9dfd373d-efd6-4c80-87a5-75f54cc54e83",
                            State = "Scheduled",
                            Time = "12:00 AM"
                        },
                        new
                        {
                            Id = new Guid("1dee1d84-0a01-4f8f-a918-fecf139e23ea"),
                            Date = "2025-05-17",
                            DoctorId = new Guid("4ca32da6-4b53-42dd-924d-fe2801ff74fc"),
                            PatientId = "5b57a12b-2656-440a-9157-6960a1051205",
                            State = "Scheduled",
                            Time = "13:00 AM"
                        },
                        new
                        {
                            Id = new Guid("58e3c660-82a6-4727-a20c-ed0a0d8c9923"),
                            Date = "2025-05-18",
                            DoctorId = new Guid("fcb2a14b-8af8-40a9-b5e7-270708a7fe9e"),
                            PatientId = "1e77598e-eb16-412e-9d18-a2f1b6256387",
                            State = "Scheduled",
                            Time = "14:00 AM"
                        },
                        new
                        {
                            Id = new Guid("bd038531-e406-4eea-ba3a-e44bd7bcb86f"),
                            Date = "2025-05-19",
                            DoctorId = new Guid("65841d01-36b4-425f-908e-4c30f3422b7d"),
                            PatientId = "cff99267-3cbb-4014-91ba-d49cf8711e08",
                            State = "Scheduled",
                            Time = "15:00 AM"
                        },
                        new
                        {
                            Id = new Guid("e730a35d-8464-4faf-bfc5-23c99fda9173"),
                            Date = "2025-05-20",
                            DoctorId = new Guid("bf46cb72-248a-454f-9fd6-38bb5c4c0b3a"),
                            PatientId = "9521e410-248f-4b6d-ba43-3473b824d8de",
                            State = "Scheduled",
                            Time = "16:00 AM"
                        });
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("95e93ba9-8feb-449a-9310-10f4f1cfa6ae"),
                            Price = 101.0,
                            Specialty = "Specialty 1",
                            UserId = "86689581-87c8-4d18-a12e-b521929851d9"
                        },
                        new
                        {
                            Id = new Guid("f8db328e-f29a-4edf-90e2-fa0af9b2f2f7"),
                            Price = 102.0,
                            Specialty = "Specialty 2",
                            UserId = "653a6b90-4762-4a70-bfbf-8ac6c4934969"
                        },
                        new
                        {
                            Id = new Guid("8eccff74-55a0-41da-b610-3bde51af8e1d"),
                            Price = 103.0,
                            Specialty = "Specialty 3",
                            UserId = "ef5e7c5b-2dff-446c-8f31-b53099ea339d"
                        },
                        new
                        {
                            Id = new Guid("35a89b32-a9f3-4d8b-b05c-e43f7d3d383d"),
                            Price = 104.0,
                            Specialty = "Specialty 4",
                            UserId = "8f1aa731-8712-40ea-b6e4-8ba29cb9f16d"
                        },
                        new
                        {
                            Id = new Guid("8ec0e9a2-5b1b-472d-bd19-b01af2e2a4b8"),
                            Price = 105.0,
                            Specialty = "Specialty 5",
                            UserId = "32366f4e-6267-4b6d-87ae-6df02db5f393"
                        },
                        new
                        {
                            Id = new Guid("586a05c8-9376-4501-873d-b79f6332874f"),
                            Price = 106.0,
                            Specialty = "Specialty 6",
                            UserId = "0aeed420-b2f6-4718-a55f-91e9014e15f3"
                        },
                        new
                        {
                            Id = new Guid("1ee3aa75-f8b2-4d41-9372-a70900e8ac7c"),
                            Price = 107.0,
                            Specialty = "Specialty 7",
                            UserId = "0a9b1a7d-d3de-4c07-bfed-f490dfb0d063"
                        },
                        new
                        {
                            Id = new Guid("6ac96d36-36e6-44f2-bbf6-6578898b494d"),
                            Price = 108.0,
                            Specialty = "Specialty 8",
                            UserId = "6201941c-43f3-4fb2-9fe0-5131071e84b8"
                        },
                        new
                        {
                            Id = new Guid("da4da8de-4558-4d72-a225-054fabbaa9da"),
                            Price = 109.0,
                            Specialty = "Specialty 9",
                            UserId = "cdad694a-e53d-4988-9301-549667be2cde"
                        },
                        new
                        {
                            Id = new Guid("5aa28e01-644d-498c-b66f-bfc2c720cb88"),
                            Price = 110.0,
                            Specialty = "Specialty 10",
                            UserId = "22d0e279-b1bd-4e5d-87d5-4ef437e35487"
                        },
                        new
                        {
                            Id = new Guid("75cb34ef-6a82-4d78-b770-70408334d8fa"),
                            Price = 111.0,
                            Specialty = "Specialty 11",
                            UserId = "9f7df074-0434-42da-8200-01a5b860c73a"
                        },
                        new
                        {
                            Id = new Guid("c4485f07-ece1-410c-af94-321edfde9425"),
                            Price = 112.0,
                            Specialty = "Specialty 12",
                            UserId = "c64eb54f-f359-48ec-8aea-1d0427f8623a"
                        },
                        new
                        {
                            Id = new Guid("d7aad276-d4c1-4bee-b695-4cba94abb37a"),
                            Price = 113.0,
                            Specialty = "Specialty 13",
                            UserId = "abb56b65-a9ac-461f-b3a1-2cb386134b78"
                        },
                        new
                        {
                            Id = new Guid("ed39d351-1002-40d0-858c-846c3f2b0764"),
                            Price = 114.0,
                            Specialty = "Specialty 14",
                            UserId = "fc0cba89-c0c6-44e1-be04-1526d0f22571"
                        },
                        new
                        {
                            Id = new Guid("951488a8-30b3-4e3c-9aeb-6c548e5349cb"),
                            Price = 115.0,
                            Specialty = "Specialty 15",
                            UserId = "494a9306-12d3-48e8-9249-49a2ace53649"
                        },
                        new
                        {
                            Id = new Guid("67457fae-0354-4697-a68f-a3c996454db8"),
                            Price = 116.0,
                            Specialty = "Specialty 16",
                            UserId = "84c82c8d-886c-4f3c-a0ae-a9f674c397a6"
                        },
                        new
                        {
                            Id = new Guid("4ca32da6-4b53-42dd-924d-fe2801ff74fc"),
                            Price = 117.0,
                            Specialty = "Specialty 17",
                            UserId = "148a40a7-da4e-4e1b-a003-9e58c0d6d485"
                        },
                        new
                        {
                            Id = new Guid("fcb2a14b-8af8-40a9-b5e7-270708a7fe9e"),
                            Price = 118.0,
                            Specialty = "Specialty 18",
                            UserId = "45453ec6-1845-4c04-b76b-641a0e1e350f"
                        },
                        new
                        {
                            Id = new Guid("65841d01-36b4-425f-908e-4c30f3422b7d"),
                            Price = 119.0,
                            Specialty = "Specialty 19",
                            UserId = "00adac97-ef12-4ee0-89d2-9668bad3e333"
                        },
                        new
                        {
                            Id = new Guid("bf46cb72-248a-454f-9fd6-38bb5c4c0b3a"),
                            Price = 120.0,
                            Specialty = "Specialty 20",
                            UserId = "46c76612-1744-4125-9fa2-404d4d586a6e"
                        });
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.FileImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("FileLength")
                        .HasColumnType("float");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PrescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId")
                        .IsUnique()
                        .HasFilter("[DoctorId] IS NOT NULL");

                    b.HasIndex("PrescriptionId")
                        .IsUnique()
                        .HasFilter("[PrescriptionId] IS NOT NULL");

                    b.ToTable("FileImages");
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modification_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ec53acd-4bbf-4cd0-8bd6-e9990d503650"),
                            AppointmentId = new Guid("e93ead83-0fd9-427e-b76c-f742c2b9bf3b"),
                            Description = "Prescription for appointment 1",
                            Modification_date = "2025-05-06"
                        },
                        new
                        {
                            Id = new Guid("37ce5be0-4c22-419c-a9d6-6416e9699984"),
                            AppointmentId = new Guid("2d6a4ecd-51b6-48b7-9f79-ac5ce492402b"),
                            Description = "Prescription for appointment 2",
                            Modification_date = "2025-05-06"
                        },
                        new
                        {
                            Id = new Guid("e92aa1c5-4047-458e-8d7a-c754b025fa97"),
                            AppointmentId = new Guid("b053a945-94de-432f-b309-818acfbb0576"),
                            Description = "Prescription for appointment 3",
                            Modification_date = "2025-05-06"
                        },
                        new
                        {
                            Id = new Guid("c6091f81-8c91-49df-aeb1-afdc562a8df4"),
                            AppointmentId = new Guid("ff562776-5ecb-49ae-961d-57ccdce8ac3e"),
                            Description = "Prescription for appointment 4",
                            Modification_date = "2025-05-06"
                        },
                        new
                        {
                            Id = new Guid("238e14b3-3bae-40ff-84b2-503cf139923c"),
                            AppointmentId = new Guid("04623cc9-a4b6-4fe7-9340-8f46df018a61"),
                            Description = "Prescription for appointment 5",
                            Modification_date = "2025-05-06"
                        },
                        new
                        {
                            Id = new Guid("1058be7e-1eb3-4fc2-81a2-b90d54273125"),
                            AppointmentId = new Guid("8debbab0-faae-4539-ac70-0055c5edbb53"),
                            Description = "Prescription for appointment 6",
                            Modification_date = "2025-05-06"
                        },
                        new
                        {
                            Id = new Guid("a80aa1eb-be5e-4016-b923-fb5f7b99796b"),
                            AppointmentId = new Guid("083f0240-a7a9-48a5-b180-19ac48bfac03"),
                            Description = "Prescription for appointment 7",
                            Modification_date = "2025-05-06"
                        },
                        new
                        {
                            Id = new Guid("b54537f3-0469-4864-9226-7aa41e1e1e1b"),
                            AppointmentId = new Guid("7a8eebfe-9f72-449b-8047-fb1f1541b37f"),
                            Description = "Prescription for appointment 8",
                            Modification_date = "2025-05-06"
                        },
                        new
                        {
                            Id = new Guid("0e460cdb-7616-4f30-8f29-42cdc887ee79"),
                            AppointmentId = new Guid("f716fdb0-5e03-4a7a-8bd5-52c3bd0c60aa"),
                            Description = "Prescription for appointment 9",
                            Modification_date = "2025-05-06"
                        },
                        new
                        {
                            Id = new Guid("b1026625-577a-4d79-8db5-fb4e0d279fbe"),
                            AppointmentId = new Guid("7985db89-7d11-4e96-967f-a1b5c54c419f"),
                            Description = "Prescription for appointment 10",
                            Modification_date = "2025-05-06"
                        },
                        new
                        {
                            Id = new Guid("1edd450e-672e-4966-b245-37b0c0ba69cd"),
                            AppointmentId = new Guid("c57e79c6-076d-4b96-99f6-7baa3ea75cb0"),
                            Description = "Prescription for appointment 11",
                            Modification_date = "2025-05-06"
                        },
                        new
                        {
                            Id = new Guid("b369c02e-a93b-4b2d-90b5-1f3cb5b5861d"),
                            AppointmentId = new Guid("2c1ff423-e321-44db-8e9a-035797b483f6"),
                            Description = "Prescription for appointment 12",
                            Modification_date = "2025-05-06"
                        },
                        new
                        {
                            Id = new Guid("b7e0f4dd-b655-41b0-ba2d-ed1d7184e43e"),
                            AppointmentId = new Guid("dc91d62a-5663-4cbf-97db-8eee9d47e832"),
                            Description = "Prescription for appointment 13",
                            Modification_date = "2025-05-06"
                        },
                        new
                        {
                            Id = new Guid("c94103b9-d260-41a7-958b-d01af023bb78"),
                            AppointmentId = new Guid("148d0b11-06be-4498-b3a1-41b431406969"),
                            Description = "Prescription for appointment 14",
                            Modification_date = "2025-05-06"
                        },
                        new
                        {
                            Id = new Guid("375ccf86-f585-42f6-8c2d-f19c9ccf8850"),
                            AppointmentId = new Guid("86988fdf-7997-4e00-8ac9-cc538275673b"),
                            Description = "Prescription for appointment 15",
                            Modification_date = "2025-05-06"
                        },
                        new
                        {
                            Id = new Guid("3accc9d6-c8a0-4786-96fb-5043e2420f64"),
                            AppointmentId = new Guid("64e03248-4402-4bed-a7ca-af53dd219328"),
                            Description = "Prescription for appointment 16",
                            Modification_date = "2025-05-06"
                        },
                        new
                        {
                            Id = new Guid("a1bd0020-3e56-415f-8b3c-d1b13a578441"),
                            AppointmentId = new Guid("1dee1d84-0a01-4f8f-a918-fecf139e23ea"),
                            Description = "Prescription for appointment 17",
                            Modification_date = "2025-05-06"
                        },
                        new
                        {
                            Id = new Guid("6753b1fb-9b1b-4037-ada6-1337eecc0a20"),
                            AppointmentId = new Guid("58e3c660-82a6-4727-a20c-ed0a0d8c9923"),
                            Description = "Prescription for appointment 18",
                            Modification_date = "2025-05-06"
                        },
                        new
                        {
                            Id = new Guid("964d02a6-3402-405a-9c01-2bf6fe518e1a"),
                            AppointmentId = new Guid("bd038531-e406-4eea-ba3a-e44bd7bcb86f"),
                            Description = "Prescription for appointment 19",
                            Modification_date = "2025-05-06"
                        },
                        new
                        {
                            Id = new Guid("6f6aeabb-0a91-4d60-a424-d07f92457e3d"),
                            AppointmentId = new Guid("e730a35d-8464-4faf-bfc5-23c99fda9173"),
                            Description = "Prescription for appointment 20",
                            Modification_date = "2025-05-06"
                        });
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.UserApplication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f90968cb-de1f-46a0-a508-0e13fef63922",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "99948ae2-fab3-454d-96fe-d6e755654911",
                            Email = "admin1@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN1@CLINIC.COM",
                            NormalizedUserName = "ADMIN1@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN4J/lKE7hbmjIQcI32Nb1sBM1XAYFTYSaqI7USgFilsQbwbmvA39JcKHLtnHPWWPA==",
                            PhoneNumber = "01000000001",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "c85420b0-e60e-47b2-9695-cd28bb8894dd",
                            TwoFactorEnabled = false,
                            UserName = "admin1@clinic.com"
                        },
                        new
                        {
                            Id = "ce05714c-0de2-4fd6-afc0-867f4aca74d8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e5b2e053-ee76-4860-87f5-1e87afda609b",
                            Email = "admin2@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN2@CLINIC.COM",
                            NormalizedUserName = "ADMIN2@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECvteeyO0yXunJ78Sou54Gr6+UGe+dznbO2rEOuD9RApxViOBoT622H/J16kTxZTLQ==",
                            PhoneNumber = "01000000002",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "b5c25ada-43b5-4d2f-957f-46fec42ea97e",
                            TwoFactorEnabled = false,
                            UserName = "admin2@clinic.com"
                        },
                        new
                        {
                            Id = "755a8257-ad4c-44ac-8e69-ae15c27eb1e0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5370ec16-f557-45fa-b06b-707bbdd3c686",
                            Email = "admin3@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN3@CLINIC.COM",
                            NormalizedUserName = "ADMIN3@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECgP5P5TyiZ2Y70PZBNw6qLFRVuOJCd4rXssqi/9Ph/ijgEsFHLExwx4MOKVG7AvVQ==",
                            PhoneNumber = "01000000003",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "81baf9b3-bc20-4e10-901a-0a0ee7c4bb25",
                            TwoFactorEnabled = false,
                            UserName = "admin3@clinic.com"
                        },
                        new
                        {
                            Id = "9f5a316e-c0f8-417c-93a7-0e8bdf371660",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8cb371f4-2072-44d9-b63c-bcc97c629525",
                            Email = "admin4@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN4@CLINIC.COM",
                            NormalizedUserName = "ADMIN4@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENPFWqNdlgYq+KiPn2mh5am5R5SK/LSGPXKoRuqR/8a9Gdc7EoD5iIvImPCnckiskQ==",
                            PhoneNumber = "01000000004",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "71417afd-faba-4d81-9950-1171cc6a6dfe",
                            TwoFactorEnabled = false,
                            UserName = "admin4@clinic.com"
                        },
                        new
                        {
                            Id = "8bb59f45-c04f-49cd-bdb1-67196483be35",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5c26d331-fc5f-498f-bb9f-9ab6e3879b06",
                            Email = "admin5@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN5@CLINIC.COM",
                            NormalizedUserName = "ADMIN5@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEC/UbeBuKgFhU4BPVbO+ysI3CM9KC7xSiEUcw1nzD6H8MvVX6N/IzUEyibPS/uWQeA==",
                            PhoneNumber = "01000000005",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "7c9f23b9-1e4a-4ef3-99f2-0acdfab1e8b9",
                            TwoFactorEnabled = false,
                            UserName = "admin5@clinic.com"
                        },
                        new
                        {
                            Id = "eee26db5-0164-495f-89f2-83ea285db8c0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8f504fa2-cd11-461f-81e7-4c194fc4c9d0",
                            Email = "patient1@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT1@CLINIC.COM",
                            NormalizedUserName = "PATIENT1@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHAENtJ49TRef2pml7QFDZriLEbKI2Y5X06K7WxGn8TnbLhhUmXYwt6WeTIp3MTpRQ==",
                            PhoneNumber = "01000000001",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1165c168-7c82-4dfd-a3bd-cf3be6c69a81",
                            TwoFactorEnabled = false,
                            UserName = "patient1@clinic.com"
                        },
                        new
                        {
                            Id = "8ca7d99f-35d7-4651-836c-d9d061a49427",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "483ae3aa-ee31-4c0e-ac98-f59ef9d8a988",
                            Email = "patient2@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT2@CLINIC.COM",
                            NormalizedUserName = "PATIENT2@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENzppQZrYZRjdmliNVatniguTpdieA5SThjtpeRTkFc0qyzXLqK7DeLWnmdrae2jQQ==",
                            PhoneNumber = "01000000002",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "741d9a2a-6c2b-4651-b05c-e660ce8117a7",
                            TwoFactorEnabled = false,
                            UserName = "patient2@clinic.com"
                        },
                        new
                        {
                            Id = "a12ab74b-ba32-4056-b607-202472f76ca2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e4a4b0fa-af51-47a5-9ba7-02b7da35e9bd",
                            Email = "patient3@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT3@CLINIC.COM",
                            NormalizedUserName = "PATIENT3@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECCNJMk7Nr+F1WmeuHaNkRZCJQQmiqes64oOynYULODa/ENPl+HhtiT8JuK5ZMM/FA==",
                            PhoneNumber = "01000000003",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "cca4ab3b-e225-4c8b-a2ca-2f788f6565bc",
                            TwoFactorEnabled = false,
                            UserName = "patient3@clinic.com"
                        },
                        new
                        {
                            Id = "931c0531-e15c-48e1-8a5c-b30c62eb50f9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2674d4ca-c2bc-48f7-93ba-9fca2219cf71",
                            Email = "patient4@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT4@CLINIC.COM",
                            NormalizedUserName = "PATIENT4@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBCJ7xY59Cl5CG8j50++REevvgg5tkma01Zd7JsoRcpnDNHjKeI3cKRCg+tJuYYtcA==",
                            PhoneNumber = "01000000004",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "b6be843c-8f3c-4c2a-937a-1b1eea6d040f",
                            TwoFactorEnabled = false,
                            UserName = "patient4@clinic.com"
                        },
                        new
                        {
                            Id = "6627e77d-6c04-4165-a1a9-8e45915006a3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1fac11e9-b59c-45da-9535-46c1cd7e0e77",
                            Email = "patient5@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT5@CLINIC.COM",
                            NormalizedUserName = "PATIENT5@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEM4BAEYfIJkT6comCaHVy4czRsuF3lBcQzdD6lI7zNUsswlsB/LC8rBh2jo81XuSuQ==",
                            PhoneNumber = "01000000005",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "b36c51f1-a07c-4b3b-b5a0-bd55a13fec63",
                            TwoFactorEnabled = false,
                            UserName = "patient5@clinic.com"
                        },
                        new
                        {
                            Id = "96ec0f2d-d4cb-46c1-a1bf-73900a1592f5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e99ca9e8-7f6f-4dfc-af41-920578843268",
                            Email = "patient6@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT6@CLINIC.COM",
                            NormalizedUserName = "PATIENT6@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPyDK6ZBFMn8HI39Da9AplU6RHosyS16wnd4vs7NSli4y+jxNPtzRhqvlq8aXxwwEw==",
                            PhoneNumber = "01000000006",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "356cccaa-2cac-492a-af97-d94f4e3760b6",
                            TwoFactorEnabled = false,
                            UserName = "patient6@clinic.com"
                        },
                        new
                        {
                            Id = "2ec8090b-edb6-42d2-9109-c8296f933566",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2055b24a-2f10-4f00-8354-a1f158c34e22",
                            Email = "patient7@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT7@CLINIC.COM",
                            NormalizedUserName = "PATIENT7@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHmS+liqDu+/Ykf+M36/H22qXCQgJEEHOe6rt+iDQf5mwWS4ew5ts1cpx+xPYG6/wg==",
                            PhoneNumber = "01000000007",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "4e36b4b7-e000-4863-a88b-b4b104c09cf1",
                            TwoFactorEnabled = false,
                            UserName = "patient7@clinic.com"
                        },
                        new
                        {
                            Id = "d750d504-86db-4df3-ba0d-f5d2bc2f213b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "65898e2d-4830-4bc0-a5b8-cc7774f7b633",
                            Email = "patient8@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT8@CLINIC.COM",
                            NormalizedUserName = "PATIENT8@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGeFOcLFHA3jDqM5kxD9SpusgtHQQgTHSlrmPuKENhtqUT8gf9UdHbS06zR2wQakHg==",
                            PhoneNumber = "01000000008",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "dcf684ae-85ee-406d-9676-f42f248011f0",
                            TwoFactorEnabled = false,
                            UserName = "patient8@clinic.com"
                        },
                        new
                        {
                            Id = "d3c97e74-8660-494a-a2af-eaa94baedfe4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "748109d0-c851-4a6a-9527-af9499ca439b",
                            Email = "patient9@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT9@CLINIC.COM",
                            NormalizedUserName = "PATIENT9@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOcXDEQUa9eoqsEa4BdyMIDY9y36nwGcrMpIIWDXWQj/vmoRyuPtyBMMgia/1pzEtA==",
                            PhoneNumber = "01000000009",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "a755d3ef-edd5-49ce-90c2-3cdb8d42b987",
                            TwoFactorEnabled = false,
                            UserName = "patient9@clinic.com"
                        },
                        new
                        {
                            Id = "023978a1-0aad-43dc-8b37-b9bfa1c69d64",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "69e708e7-01db-461b-a715-1c363001c960",
                            Email = "patient10@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT10@CLINIC.COM",
                            NormalizedUserName = "PATIENT10@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEH4ETVRLxHCaVmU+LwBrtJ1rNH1ts/Gf8Iu/Tx4kEgwW6xZJIEizNGcnq4jHxLKsBA==",
                            PhoneNumber = "01000000010",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "26db7d63-fa30-4941-9ccb-05d9d828efa2",
                            TwoFactorEnabled = false,
                            UserName = "patient10@clinic.com"
                        },
                        new
                        {
                            Id = "9dfd373d-efd6-4c80-87a5-75f54cc54e83",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c4829006-0234-4e2e-8c63-be92b40081e8",
                            Email = "patient11@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT11@CLINIC.COM",
                            NormalizedUserName = "PATIENT11@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEOPBau/q15hxxai2/dGSRwsxBsTfGCHFTg/MFwiiVsrgfaKADcQ3YW+qdqXqIRN8A==",
                            PhoneNumber = "01000000011",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "72b1050a-f48c-4c74-a618-96dab87d1424",
                            TwoFactorEnabled = false,
                            UserName = "patient11@clinic.com"
                        },
                        new
                        {
                            Id = "5b57a12b-2656-440a-9157-6960a1051205",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3306f121-0687-4531-8413-b5bb38aa4d93",
                            Email = "patient12@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT12@CLINIC.COM",
                            NormalizedUserName = "PATIENT12@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECjr7jaj2lSvYpurbXiMYNTrSAbjnOEl8+I+naL1U1XNNtN/z3YdmFWQazx219kaXg==",
                            PhoneNumber = "01000000012",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "fab79c2f-979e-4f01-a60b-476a1a2e4e41",
                            TwoFactorEnabled = false,
                            UserName = "patient12@clinic.com"
                        },
                        new
                        {
                            Id = "1e77598e-eb16-412e-9d18-a2f1b6256387",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ac06e920-db91-4e89-844b-c71bfa73e958",
                            Email = "patient13@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT13@CLINIC.COM",
                            NormalizedUserName = "PATIENT13@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPcFYBTmBEvKfLjTfTq5zG0uZ6rGtywLfcJlvcqMqJ5Yo3prhY1I3WC87WAX3aQFqQ==",
                            PhoneNumber = "01000000013",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1ac59bc2-5254-4ceb-b8ed-a8926831d816",
                            TwoFactorEnabled = false,
                            UserName = "patient13@clinic.com"
                        },
                        new
                        {
                            Id = "cff99267-3cbb-4014-91ba-d49cf8711e08",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a353c530-2f5e-4c78-8f03-73b9b3474f26",
                            Email = "patient14@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT14@CLINIC.COM",
                            NormalizedUserName = "PATIENT14@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDJEm7KDG4+ugKajd9L8SCoiYfSvdqtfkwjnSzYQRvml1QjEB642o7lbwnCLoxODRg==",
                            PhoneNumber = "01000000014",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "9cf1fc86-5612-4db9-b867-60988adbbb11",
                            TwoFactorEnabled = false,
                            UserName = "patient14@clinic.com"
                        },
                        new
                        {
                            Id = "9521e410-248f-4b6d-ba43-3473b824d8de",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fbd66233-a86e-4c4d-b468-9527b37be8dd",
                            Email = "patient15@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT15@CLINIC.COM",
                            NormalizedUserName = "PATIENT15@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDUDxf/gPrUcqsxHNDkHlexXUmlW/W9g3fWevhiKO2ghgd7tuF6zWojIbKrTAUPk4g==",
                            PhoneNumber = "01000000015",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "2f903a68-6bdc-46b6-8be0-03c5096ee89b",
                            TwoFactorEnabled = false,
                            UserName = "patient15@clinic.com"
                        },
                        new
                        {
                            Id = "7a899aed-90ea-4e2c-9e63-f9694ca2b3bd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1b742baa-35bd-4ed4-bd9f-8ace131f458c",
                            Email = "patient16@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT16@CLINIC.COM",
                            NormalizedUserName = "PATIENT16@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKYKNw7vx4LjBcdApaamSyvnqHp1kxxsMPtyS1MjO302F/NeBf/LeEvJmy3/wA0SBg==",
                            PhoneNumber = "01000000016",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "87316bb2-9b76-405c-8547-642810c83048",
                            TwoFactorEnabled = false,
                            UserName = "patient16@clinic.com"
                        },
                        new
                        {
                            Id = "bedfbe7e-17eb-4a27-b5e9-f8a0fc41ec34",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "51b80271-6446-4119-a300-331ba3bef56d",
                            Email = "patient17@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT17@CLINIC.COM",
                            NormalizedUserName = "PATIENT17@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPchwvtbcQB6eTDSGq7hTOoxI8xElYFJp/5JGl0Jr4FDwlu1QqqAe8v5vjBAUZ9aWw==",
                            PhoneNumber = "01000000017",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "4a501771-3eb5-4561-b6cc-bbc18aabbebe",
                            TwoFactorEnabled = false,
                            UserName = "patient17@clinic.com"
                        },
                        new
                        {
                            Id = "0e97bb17-b2c1-467d-8774-411fa6799da5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "df2e33e2-5241-4bcf-8c7a-313effd5d019",
                            Email = "patient18@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT18@CLINIC.COM",
                            NormalizedUserName = "PATIENT18@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMSyMelgoiJZb4CuJNp8iek0HBXs1CuuN9YN9/8BLET4MKnKJ2xmwNP6fq3o4NHH9g==",
                            PhoneNumber = "01000000018",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "7db2c316-f436-41f9-901d-6a5baf2382df",
                            TwoFactorEnabled = false,
                            UserName = "patient18@clinic.com"
                        },
                        new
                        {
                            Id = "413a2466-e957-431c-837c-20a44fae1d27",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "56962d5f-12df-483f-9040-dcaf852e3fb6",
                            Email = "patient19@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT19@CLINIC.COM",
                            NormalizedUserName = "PATIENT19@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIE8GDPwDX8WSlVIKq9T93elJBqANszrnEFM4OibdOG74qLBnQ1DxBdfFdxwlD4blw==",
                            PhoneNumber = "01000000019",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "150bdc58-f959-443d-bbdc-ca6d52e5511b",
                            TwoFactorEnabled = false,
                            UserName = "patient19@clinic.com"
                        },
                        new
                        {
                            Id = "39344909-14a6-4fec-b23e-9e2269cfe94f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "530afed5-bea3-4fad-846b-a91e36a30e5c",
                            Email = "patient20@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT20@CLINIC.COM",
                            NormalizedUserName = "PATIENT20@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECaIxLRlyHe+vJnBai1zyzrM4kdjYlEpVkIL8j2dIBIHWV7AtiaKjFzOmceDuoMG5w==",
                            PhoneNumber = "01000000020",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "86f5f857-1733-4163-a17b-38d32e5a5318",
                            TwoFactorEnabled = false,
                            UserName = "patient20@clinic.com"
                        },
                        new
                        {
                            Id = "86689581-87c8-4d18-a12e-b521929851d9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7702d2a9-6e59-43e6-bcf9-04d867e0ae2f",
                            Email = "doctor1@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR1@CLINIC.COM",
                            NormalizedUserName = "DOCTOR1@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEG+kzIuKR5vUPTBuEZMSYXQ0Tf8aLyDvoVCo/S2KSOrnF9jaAD4bPKuT2ORGLsnJfA==",
                            PhoneNumber = "01100000001",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "f042a74f-493c-4003-af7a-20edbdcbcc05",
                            TwoFactorEnabled = false,
                            UserName = "doctor1@clinic.com"
                        },
                        new
                        {
                            Id = "653a6b90-4762-4a70-bfbf-8ac6c4934969",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d0b83f48-85a9-4372-98b8-7bae558ca7a9",
                            Email = "doctor2@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR2@CLINIC.COM",
                            NormalizedUserName = "DOCTOR2@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEI77FwBM9kFuFUeiZoghSgHGaZ9BNjc6IfDMT5nGjVPu2Pur5gR6XApYVTZqSOwIGg==",
                            PhoneNumber = "01100000002",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "20579d53-bfaf-4e26-bbd4-48a99dd990b9",
                            TwoFactorEnabled = false,
                            UserName = "doctor2@clinic.com"
                        },
                        new
                        {
                            Id = "ef5e7c5b-2dff-446c-8f31-b53099ea339d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "baf66f10-6ea2-49a5-8a0e-087fa491f604",
                            Email = "doctor3@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR3@CLINIC.COM",
                            NormalizedUserName = "DOCTOR3@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGlQVeI1QkXflklRvQ4mEqq5zSjLbVJUWlvXN4wd+4aZtHAf81gdo0UOxJqFsykIng==",
                            PhoneNumber = "01100000003",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "755097b7-1c6b-4bc7-be77-1db83b854cb7",
                            TwoFactorEnabled = false,
                            UserName = "doctor3@clinic.com"
                        },
                        new
                        {
                            Id = "8f1aa731-8712-40ea-b6e4-8ba29cb9f16d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "df70c137-910c-491b-a070-2d6a217955df",
                            Email = "doctor4@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR4@CLINIC.COM",
                            NormalizedUserName = "DOCTOR4@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEB6hFq+d0gYxFMjBirOBUNdUMszmbd4OH/DaboEY7m8E9fOH6muAVNmPg1x4G5fWQ==",
                            PhoneNumber = "01100000004",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "a717cfaf-0000-4e4c-be1f-c5c10f7eff35",
                            TwoFactorEnabled = false,
                            UserName = "doctor4@clinic.com"
                        },
                        new
                        {
                            Id = "32366f4e-6267-4b6d-87ae-6df02db5f393",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3d71fdb4-931e-4130-858c-519fa788c315",
                            Email = "doctor5@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR5@CLINIC.COM",
                            NormalizedUserName = "DOCTOR5@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBnvXY3zlmVLaz/hBY9lNxxIhV2QV9cdp8DcIKRUR3e/tbPo2QpGK/V4hJD75MYH1A==",
                            PhoneNumber = "01100000005",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "d29dc125-5dc1-4bc9-a758-1b824be6266b",
                            TwoFactorEnabled = false,
                            UserName = "doctor5@clinic.com"
                        },
                        new
                        {
                            Id = "0aeed420-b2f6-4718-a55f-91e9014e15f3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "80597ec7-9f93-4242-824a-9336ac18f33a",
                            Email = "doctor6@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR6@CLINIC.COM",
                            NormalizedUserName = "DOCTOR6@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPuwynyLF26dIzf2jiCzVBIeB+wILgT7eQIh5fdymsjclD3Vad9pN6VN0T5IORCSlA==",
                            PhoneNumber = "01100000006",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "dc146ab2-bc5d-4ade-8c52-79b61a81e666",
                            TwoFactorEnabled = false,
                            UserName = "doctor6@clinic.com"
                        },
                        new
                        {
                            Id = "0a9b1a7d-d3de-4c07-bfed-f490dfb0d063",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8619676a-cebf-4e65-93f7-7446e70da021",
                            Email = "doctor7@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR7@CLINIC.COM",
                            NormalizedUserName = "DOCTOR7@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBF0Xmg1xRnIOnSt72l+YyWj3GnjRgbNl7F/1l5aps75nOi0XMKiFeVdXfAy/EUivQ==",
                            PhoneNumber = "01100000007",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "75d19d7d-62d3-4020-9b11-72e633146463",
                            TwoFactorEnabled = false,
                            UserName = "doctor7@clinic.com"
                        },
                        new
                        {
                            Id = "6201941c-43f3-4fb2-9fe0-5131071e84b8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c3f76ca2-ec8f-42d0-8bb9-0a115a9502e5",
                            Email = "doctor8@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR8@CLINIC.COM",
                            NormalizedUserName = "DOCTOR8@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEE3NmMbDUC2B2ARG4/yrTjulWRNfLd5m9uua0wUVp8qxPV4kGwc/UBBxF8IGN3IBrg==",
                            PhoneNumber = "01100000008",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "17858c4d-8165-4526-9d8b-2f72d3d65c4d",
                            TwoFactorEnabled = false,
                            UserName = "doctor8@clinic.com"
                        },
                        new
                        {
                            Id = "cdad694a-e53d-4988-9301-549667be2cde",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ee95e38c-557e-4064-a4cc-c143b1bb4172",
                            Email = "doctor9@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR9@CLINIC.COM",
                            NormalizedUserName = "DOCTOR9@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAtbmwY7ml9qaCYSzdnBARIl+y5Q4T9CWF70N4jHQr9y76AKiCG8bJkA2Dyb9iWcrg==",
                            PhoneNumber = "01100000009",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "882eaafd-9e58-4e51-ab68-235e806f0ddd",
                            TwoFactorEnabled = false,
                            UserName = "doctor9@clinic.com"
                        },
                        new
                        {
                            Id = "22d0e279-b1bd-4e5d-87d5-4ef437e35487",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "952d42a9-726c-42ac-b599-d931dd4f2621",
                            Email = "doctor10@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR10@CLINIC.COM",
                            NormalizedUserName = "DOCTOR10@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFaK2iUCqzB+aGfzFQtEwwDnXlq3IqyT4z1wPN3RNBYKls/e4ETJMC2DsM8VaspNRA==",
                            PhoneNumber = "01100000010",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "33e3fa92-c9dc-4aea-9e55-e30222d723af",
                            TwoFactorEnabled = false,
                            UserName = "doctor10@clinic.com"
                        },
                        new
                        {
                            Id = "9f7df074-0434-42da-8200-01a5b860c73a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "43b70b94-0b2c-4d1d-b814-92b3d9d737dc",
                            Email = "doctor11@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR11@CLINIC.COM",
                            NormalizedUserName = "DOCTOR11@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAiPuhjnXc+B+H4Xzhur/8qjeexv4h9cea2Lg7Pi2QdfIx2J8KxW/QStACnSxv7vuw==",
                            PhoneNumber = "01100000011",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "7211e03a-feec-4872-83e2-2f43b03fc456",
                            TwoFactorEnabled = false,
                            UserName = "doctor11@clinic.com"
                        },
                        new
                        {
                            Id = "c64eb54f-f359-48ec-8aea-1d0427f8623a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e6e48fae-7c78-4f75-ae76-ae681578f5fd",
                            Email = "doctor12@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR12@CLINIC.COM",
                            NormalizedUserName = "DOCTOR12@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAED/Gu+DrzWtgvQDTDM6ROVMLk+6XEqRHog+5D1nfDasGQbKJdeI6rfu47pNC4i2QPA==",
                            PhoneNumber = "01100000012",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1e511226-a192-4614-9b87-091252ed10e4",
                            TwoFactorEnabled = false,
                            UserName = "doctor12@clinic.com"
                        },
                        new
                        {
                            Id = "abb56b65-a9ac-461f-b3a1-2cb386134b78",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dcc2fbf7-9200-432b-b0e1-5ed5a47fd032",
                            Email = "doctor13@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR13@CLINIC.COM",
                            NormalizedUserName = "DOCTOR13@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA76IurAA4uj/RukMagARlzHfKuaJnCzvmmVW+THAwws0yx7dlP7KwIpxGXY9r5Exg==",
                            PhoneNumber = "01100000013",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "2a9fdae8-408e-4b28-b203-4f3ea6a86f6b",
                            TwoFactorEnabled = false,
                            UserName = "doctor13@clinic.com"
                        },
                        new
                        {
                            Id = "fc0cba89-c0c6-44e1-be04-1526d0f22571",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e88fdfb3-1892-4c21-9232-c3cbbc97fcbc",
                            Email = "doctor14@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR14@CLINIC.COM",
                            NormalizedUserName = "DOCTOR14@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEL7u5vkWFVs5gp/3siBMMPhGctPw6Ku7prAUtJ/A2PAbNHGtdbNmJx9SYn6kHRQAfw==",
                            PhoneNumber = "01100000014",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "a5a30f16-161b-47c2-b68a-e7e648fbffae",
                            TwoFactorEnabled = false,
                            UserName = "doctor14@clinic.com"
                        },
                        new
                        {
                            Id = "494a9306-12d3-48e8-9249-49a2ace53649",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "81ee8b45-775e-4fb3-bbde-d14ce413a738",
                            Email = "doctor15@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR15@CLINIC.COM",
                            NormalizedUserName = "DOCTOR15@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAVz3daxjv29B4F1BszIsTBtG5RIsV6G6/nN2BXKs7HFJ7J+e0JHC4w6H4s37C5e+A==",
                            PhoneNumber = "01100000015",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "e29cd504-f45b-46d3-9045-e57623a364e1",
                            TwoFactorEnabled = false,
                            UserName = "doctor15@clinic.com"
                        },
                        new
                        {
                            Id = "84c82c8d-886c-4f3c-a0ae-a9f674c397a6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "86750616-8fc7-4313-a252-8008d7840b2b",
                            Email = "doctor16@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR16@CLINIC.COM",
                            NormalizedUserName = "DOCTOR16@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIW2sRDy7+U+35PiisjNw6GEdcX8jTlk5yjsVyq4nMQpto4HMaN2VQI11vrXucDhTA==",
                            PhoneNumber = "01100000016",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "69cd2e32-a286-4147-9ca9-4281c4afa333",
                            TwoFactorEnabled = false,
                            UserName = "doctor16@clinic.com"
                        },
                        new
                        {
                            Id = "148a40a7-da4e-4e1b-a003-9e58c0d6d485",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "986ae99b-79bc-4a98-af8e-fa0b333e2509",
                            Email = "doctor17@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR17@CLINIC.COM",
                            NormalizedUserName = "DOCTOR17@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ94yMuT9LTSiadpZihYJk+FJIlxJ0hVYV6qvp38ZW3/hT0bG6rGZMrjOcCfSBOd3g==",
                            PhoneNumber = "01100000017",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "9c91c9a7-e4b6-45ca-967c-342648b0d747",
                            TwoFactorEnabled = false,
                            UserName = "doctor17@clinic.com"
                        },
                        new
                        {
                            Id = "45453ec6-1845-4c04-b76b-641a0e1e350f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cc4b80be-159e-4a60-bb8f-d1e1baa440a7",
                            Email = "doctor18@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR18@CLINIC.COM",
                            NormalizedUserName = "DOCTOR18@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOZ6nyGUWd2tqZmmGqbvH2NLFK+IMtNfrL2Iwj4Vf9Z2rFMrlZZFdfXXaJMGWk68nA==",
                            PhoneNumber = "01100000018",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "b403a021-ef27-4383-8481-e190a52b4413",
                            TwoFactorEnabled = false,
                            UserName = "doctor18@clinic.com"
                        },
                        new
                        {
                            Id = "00adac97-ef12-4ee0-89d2-9668bad3e333",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e005fc72-9795-4090-a38e-b1d3128c1266",
                            Email = "doctor19@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR19@CLINIC.COM",
                            NormalizedUserName = "DOCTOR19@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKhVcNEkg53lL8lv5y/MkIB54vetfiShRh3VT9b2BIuLSeB6V+FblRlQ8pXGOhgbkQ==",
                            PhoneNumber = "01100000019",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "37a52fe9-6b03-4f80-b7c4-e21489e9a22e",
                            TwoFactorEnabled = false,
                            UserName = "doctor19@clinic.com"
                        },
                        new
                        {
                            Id = "46c76612-1744-4125-9fa2-404d4d586a6e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bdfdef9b-14f7-4c62-98b5-289a8eb9062c",
                            Email = "doctor20@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR20@CLINIC.COM",
                            NormalizedUserName = "DOCTOR20@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBl+DMPknJdq6MUDy9KYsJC+S2DfcDiuPr6Dddj85cAYHUew3zWGHhGgUw0uL9clAQ==",
                            PhoneNumber = "01100000020",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1c8cb472-61c1-412d-a84c-0be4fc63df34",
                            TwoFactorEnabled = false,
                            UserName = "doctor20@clinic.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "675b578c-8739-4b1b-a706-816fb14910bd",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "72235979-4cb2-4bb1-9de9-9e931f98610e",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "f90968cb-de1f-46a0-a508-0e13fef63922",
                            RoleId = "675b578c-8739-4b1b-a706-816fb14910bd"
                        },
                        new
                        {
                            UserId = "ce05714c-0de2-4fd6-afc0-867f4aca74d8",
                            RoleId = "675b578c-8739-4b1b-a706-816fb14910bd"
                        },
                        new
                        {
                            UserId = "755a8257-ad4c-44ac-8e69-ae15c27eb1e0",
                            RoleId = "675b578c-8739-4b1b-a706-816fb14910bd"
                        },
                        new
                        {
                            UserId = "9f5a316e-c0f8-417c-93a7-0e8bdf371660",
                            RoleId = "675b578c-8739-4b1b-a706-816fb14910bd"
                        },
                        new
                        {
                            UserId = "8bb59f45-c04f-49cd-bdb1-67196483be35",
                            RoleId = "675b578c-8739-4b1b-a706-816fb14910bd"
                        },
                        new
                        {
                            UserId = "eee26db5-0164-495f-89f2-83ea285db8c0",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "8ca7d99f-35d7-4651-836c-d9d061a49427",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "a12ab74b-ba32-4056-b607-202472f76ca2",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "931c0531-e15c-48e1-8a5c-b30c62eb50f9",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "6627e77d-6c04-4165-a1a9-8e45915006a3",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "96ec0f2d-d4cb-46c1-a1bf-73900a1592f5",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "2ec8090b-edb6-42d2-9109-c8296f933566",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "d750d504-86db-4df3-ba0d-f5d2bc2f213b",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "d3c97e74-8660-494a-a2af-eaa94baedfe4",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "023978a1-0aad-43dc-8b37-b9bfa1c69d64",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "9dfd373d-efd6-4c80-87a5-75f54cc54e83",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "5b57a12b-2656-440a-9157-6960a1051205",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "1e77598e-eb16-412e-9d18-a2f1b6256387",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "cff99267-3cbb-4014-91ba-d49cf8711e08",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "9521e410-248f-4b6d-ba43-3473b824d8de",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "7a899aed-90ea-4e2c-9e63-f9694ca2b3bd",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "bedfbe7e-17eb-4a27-b5e9-f8a0fc41ec34",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "0e97bb17-b2c1-467d-8774-411fa6799da5",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "413a2466-e957-431c-837c-20a44fae1d27",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "39344909-14a6-4fec-b23e-9e2269cfe94f",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "86689581-87c8-4d18-a12e-b521929851d9",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "653a6b90-4762-4a70-bfbf-8ac6c4934969",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "ef5e7c5b-2dff-446c-8f31-b53099ea339d",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "8f1aa731-8712-40ea-b6e4-8ba29cb9f16d",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "32366f4e-6267-4b6d-87ae-6df02db5f393",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "0aeed420-b2f6-4718-a55f-91e9014e15f3",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "0a9b1a7d-d3de-4c07-bfed-f490dfb0d063",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "6201941c-43f3-4fb2-9fe0-5131071e84b8",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "cdad694a-e53d-4988-9301-549667be2cde",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "22d0e279-b1bd-4e5d-87d5-4ef437e35487",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "9f7df074-0434-42da-8200-01a5b860c73a",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "c64eb54f-f359-48ec-8aea-1d0427f8623a",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "abb56b65-a9ac-461f-b3a1-2cb386134b78",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "fc0cba89-c0c6-44e1-be04-1526d0f22571",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "494a9306-12d3-48e8-9249-49a2ace53649",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "84c82c8d-886c-4f3c-a0ae-a9f674c397a6",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "148a40a7-da4e-4e1b-a003-9e58c0d6d485",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "45453ec6-1845-4c04-b76b-641a0e1e350f",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "00adac97-ef12-4ee0-89d2-9668bad3e333",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "46c76612-1744-4125-9fa2-404d4d586a6e",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Appointment", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Doctor", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", "userApplication")
                        .WithOne()
                        .HasForeignKey("ClinicAPI.Models.Domain.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userApplication");
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.FileImage", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.Doctor", "Doctor")
                        .WithOne("FileImage")
                        .HasForeignKey("ClinicAPI.Models.Domain.FileImage", "DoctorId");

                    b.HasOne("ClinicAPI.Models.Domain.Prescription", "Prescription")
                        .WithOne("FileImage")
                        .HasForeignKey("ClinicAPI.Models.Domain.FileImage", "PrescriptionId");

                    b.Navigation("Doctor");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Prescription", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.Appointment", "Appointment")
                        .WithOne("Prescription")
                        .HasForeignKey("ClinicAPI.Models.Domain.Prescription", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Appointment", b =>
                {
                    b.Navigation("Prescription")
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("FileImage")
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Prescription", b =>
                {
                    b.Navigation("FileImage")
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.UserApplication", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
