// <auto-generated />
using System;
using ClinicAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicAPI.Models.Domain.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PatientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49908c9e-d1c6-4c18-b0f0-40327cf45dca"),
                            Date = "2025-05-01",
                            DoctorId = new Guid("f4e7dabf-894c-4971-9363-05416e0027d0"),
                            PatientId = "155af4cd-9869-4ae2-bf58-5c743184adc9",
                            State = "Scheduled",
                            Time = "9:00 AM"
                        },
                        new
                        {
                            Id = new Guid("dd4bdfb7-a500-4ce2-8888-b449a268eb29"),
                            Date = "2025-05-02",
                            DoctorId = new Guid("5f15c5a4-435c-46a2-b7fe-f68ac615f3d9"),
                            PatientId = "83519268-6998-43f9-b36e-52a61fd2ebea",
                            State = "Scheduled",
                            Time = "10:00 AM"
                        },
                        new
                        {
                            Id = new Guid("8a907523-ab91-408d-894e-800302e25591"),
                            Date = "2025-05-03",
                            DoctorId = new Guid("21068e8e-8129-4cb0-a74e-75bd69d1ef9e"),
                            PatientId = "0dd15ea2-0b87-4a71-a344-822c4f81c31b",
                            State = "Scheduled",
                            Time = "11:00 AM"
                        },
                        new
                        {
                            Id = new Guid("45adfd40-9894-425e-9750-0d04e1fa31cf"),
                            Date = "2025-05-04",
                            DoctorId = new Guid("0dcb619d-545f-4542-b8ba-244c8dc886e6"),
                            PatientId = "a4779ae0-81c9-46b7-b989-709460127449",
                            State = "Scheduled",
                            Time = "12:00 AM"
                        },
                        new
                        {
                            Id = new Guid("b4c4b0e8-3ddb-405c-a2ad-de661735065b"),
                            Date = "2025-05-05",
                            DoctorId = new Guid("e63f7ca7-ae0b-40ea-a92e-2d5649746b47"),
                            PatientId = "4e1b7bf2-f505-4c17-944b-4455e450adc2",
                            State = "Scheduled",
                            Time = "13:00 AM"
                        },
                        new
                        {
                            Id = new Guid("0543724f-5b29-4a27-b7c7-6a6665fc5c2e"),
                            Date = "2025-05-06",
                            DoctorId = new Guid("8954939b-d108-4541-ab33-5040dea77a2a"),
                            PatientId = "d13b4c2f-13ca-4f64-8ffc-9be8489b923e",
                            State = "Scheduled",
                            Time = "14:00 AM"
                        },
                        new
                        {
                            Id = new Guid("d4a65d73-7a7b-467e-b525-03389c3dd8df"),
                            Date = "2025-05-07",
                            DoctorId = new Guid("71fa449f-b3a8-4058-9783-206211aae399"),
                            PatientId = "1c163814-12e4-47d8-aa17-68bcbdbf897a",
                            State = "Scheduled",
                            Time = "15:00 AM"
                        },
                        new
                        {
                            Id = new Guid("7e6f1328-0bb7-4245-866f-9e9bab8801a9"),
                            Date = "2025-05-08",
                            DoctorId = new Guid("ceab535d-051a-4c24-9824-d61940ccd8e2"),
                            PatientId = "b728a214-1340-475f-b13a-c62e618669b2",
                            State = "Scheduled",
                            Time = "16:00 AM"
                        },
                        new
                        {
                            Id = new Guid("e768c293-9fc2-436f-896a-2be868e7e35d"),
                            Date = "2025-05-09",
                            DoctorId = new Guid("bcb929a5-f78f-4037-af2a-ab83825819b2"),
                            PatientId = "a9d51468-2a82-41cc-9503-2662a256a4b4",
                            State = "Scheduled",
                            Time = "17:00 AM"
                        },
                        new
                        {
                            Id = new Guid("3ba70cd3-fa33-49c8-8d3b-bc3ebb5ab5e6"),
                            Date = "2025-05-10",
                            DoctorId = new Guid("acd364c0-2600-45f3-9286-8ea9c26d99bf"),
                            PatientId = "4896696a-191d-4bdf-a628-55ec955890c8",
                            State = "Scheduled",
                            Time = "18:00 AM"
                        },
                        new
                        {
                            Id = new Guid("14ccac34-95b0-4263-ad0a-691777ba05fd"),
                            Date = "2025-05-11",
                            DoctorId = new Guid("61d25a72-8d70-4164-a8c6-56eb8d3c502b"),
                            PatientId = "c69e9027-ee3b-456c-876f-209a391adafe",
                            State = "Scheduled",
                            Time = "19:00 AM"
                        },
                        new
                        {
                            Id = new Guid("7ca31116-8dae-48d8-b0ea-53deda6916cb"),
                            Date = "2025-05-12",
                            DoctorId = new Guid("e7f2ae3d-4354-4fc7-86aa-4c023557fef7"),
                            PatientId = "bbc7e4b4-8cd2-4ec9-8fc0-4d171783972d",
                            State = "Scheduled",
                            Time = "20:00 AM"
                        },
                        new
                        {
                            Id = new Guid("cec7123b-5f10-4a0b-9444-cc6fac7fff15"),
                            Date = "2025-05-13",
                            DoctorId = new Guid("1503e0d0-f89d-4f39-af48-401a94804ed9"),
                            PatientId = "d3d69fd0-f486-482d-a248-e4ef7ed938da",
                            State = "Scheduled",
                            Time = "9:00 AM"
                        },
                        new
                        {
                            Id = new Guid("2d8947f4-de8c-48aa-9f46-664c51c82ccc"),
                            Date = "2025-05-14",
                            DoctorId = new Guid("2acd9da2-9f47-447f-93fc-ed01eac15e76"),
                            PatientId = "27bc3900-c570-42a9-968a-388cc321ce04",
                            State = "Scheduled",
                            Time = "10:00 AM"
                        },
                        new
                        {
                            Id = new Guid("bd590969-6632-4e59-8bc4-7722f64f7dbd"),
                            Date = "2025-05-15",
                            DoctorId = new Guid("dd2c460f-1676-46cb-a4fa-74968e721cbd"),
                            PatientId = "50583878-1af1-4c74-bc91-47bb6eb09889",
                            State = "Scheduled",
                            Time = "11:00 AM"
                        },
                        new
                        {
                            Id = new Guid("6ae2157d-1e58-4543-a7a6-8bb2cea19f86"),
                            Date = "2025-05-16",
                            DoctorId = new Guid("6d14cbd4-a354-4481-b918-706732e1405e"),
                            PatientId = "be8a8bb7-c229-467c-988b-5934ceaa1432",
                            State = "Scheduled",
                            Time = "12:00 AM"
                        },
                        new
                        {
                            Id = new Guid("d3a060a8-b02a-4109-9fd0-158025c58cfd"),
                            Date = "2025-05-17",
                            DoctorId = new Guid("f17bdbd8-26b4-4e1e-be73-9114360bb881"),
                            PatientId = "1e04d179-7281-4106-8744-88dc51d83d78",
                            State = "Scheduled",
                            Time = "13:00 AM"
                        },
                        new
                        {
                            Id = new Guid("6f0a43d4-4ac9-4dfe-9690-e136dc8a35ac"),
                            Date = "2025-05-18",
                            DoctorId = new Guid("fb64d66d-adc7-45f6-918d-33060785c27d"),
                            PatientId = "471ff9a6-382a-42d5-ae41-5350c22d3056",
                            State = "Scheduled",
                            Time = "14:00 AM"
                        },
                        new
                        {
                            Id = new Guid("9545615a-c638-461a-9680-9883bfb3c59b"),
                            Date = "2025-05-19",
                            DoctorId = new Guid("ce2b3ac0-85f1-4018-8a8e-2546ba347125"),
                            PatientId = "9ea01535-9542-444a-872f-08d09cb4b654",
                            State = "Scheduled",
                            Time = "15:00 AM"
                        },
                        new
                        {
                            Id = new Guid("28481353-9f09-44c0-aeae-625e4200468f"),
                            Date = "2025-05-20",
                            DoctorId = new Guid("a3f47e3f-eed3-40cf-9255-3aff83c64014"),
                            PatientId = "3c429440-8760-40f6-9aa6-cfed9f0c197a",
                            State = "Scheduled",
                            Time = "16:00 AM"
                        });
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4e7dabf-894c-4971-9363-05416e0027d0"),
                            Price = 101.0,
                            Specialty = "Specialty 1",
                            UserId = "54313667-8d2c-444e-8dc3-291a46c27d0c"
                        },
                        new
                        {
                            Id = new Guid("5f15c5a4-435c-46a2-b7fe-f68ac615f3d9"),
                            Price = 102.0,
                            Specialty = "Specialty 2",
                            UserId = "4bcbf4c1-97c3-4672-9613-73adec3ac42e"
                        },
                        new
                        {
                            Id = new Guid("21068e8e-8129-4cb0-a74e-75bd69d1ef9e"),
                            Price = 103.0,
                            Specialty = "Specialty 3",
                            UserId = "3b98d85c-0738-4834-91d6-ff8243b6bb78"
                        },
                        new
                        {
                            Id = new Guid("0dcb619d-545f-4542-b8ba-244c8dc886e6"),
                            Price = 104.0,
                            Specialty = "Specialty 4",
                            UserId = "388a7b3c-6bf5-4bed-a8e2-c94d4748ee73"
                        },
                        new
                        {
                            Id = new Guid("e63f7ca7-ae0b-40ea-a92e-2d5649746b47"),
                            Price = 105.0,
                            Specialty = "Specialty 5",
                            UserId = "9e395a1b-9a82-46a2-8b36-7e11ea2afc8f"
                        },
                        new
                        {
                            Id = new Guid("8954939b-d108-4541-ab33-5040dea77a2a"),
                            Price = 106.0,
                            Specialty = "Specialty 6",
                            UserId = "332f34b3-de2d-4319-882a-d5b5e6257f31"
                        },
                        new
                        {
                            Id = new Guid("71fa449f-b3a8-4058-9783-206211aae399"),
                            Price = 107.0,
                            Specialty = "Specialty 7",
                            UserId = "48b56279-bb35-4703-92a4-4ae6788693e0"
                        },
                        new
                        {
                            Id = new Guid("ceab535d-051a-4c24-9824-d61940ccd8e2"),
                            Price = 108.0,
                            Specialty = "Specialty 8",
                            UserId = "cf6e8fc8-6d58-456e-86ca-c61a518f9636"
                        },
                        new
                        {
                            Id = new Guid("bcb929a5-f78f-4037-af2a-ab83825819b2"),
                            Price = 109.0,
                            Specialty = "Specialty 9",
                            UserId = "08fa64d7-4992-4b42-bc61-543bae5f14fe"
                        },
                        new
                        {
                            Id = new Guid("acd364c0-2600-45f3-9286-8ea9c26d99bf"),
                            Price = 110.0,
                            Specialty = "Specialty 10",
                            UserId = "239278b6-d460-46d5-a67b-65b2ea8bff56"
                        },
                        new
                        {
                            Id = new Guid("61d25a72-8d70-4164-a8c6-56eb8d3c502b"),
                            Price = 111.0,
                            Specialty = "Specialty 11",
                            UserId = "f8630862-4ec6-4b00-a1ad-10b319de03c1"
                        },
                        new
                        {
                            Id = new Guid("e7f2ae3d-4354-4fc7-86aa-4c023557fef7"),
                            Price = 112.0,
                            Specialty = "Specialty 12",
                            UserId = "208a800c-b8bc-4f7c-aa27-b1f5d1f75ce0"
                        },
                        new
                        {
                            Id = new Guid("1503e0d0-f89d-4f39-af48-401a94804ed9"),
                            Price = 113.0,
                            Specialty = "Specialty 13",
                            UserId = "9f27b9fb-1ba1-45ee-a85d-c3b190b2fc44"
                        },
                        new
                        {
                            Id = new Guid("2acd9da2-9f47-447f-93fc-ed01eac15e76"),
                            Price = 114.0,
                            Specialty = "Specialty 14",
                            UserId = "7ac5d4de-d0fd-4958-bc83-dd478b22e4f5"
                        },
                        new
                        {
                            Id = new Guid("dd2c460f-1676-46cb-a4fa-74968e721cbd"),
                            Price = 115.0,
                            Specialty = "Specialty 15",
                            UserId = "9c825ad4-18e1-4368-8dbc-329f78534d91"
                        },
                        new
                        {
                            Id = new Guid("6d14cbd4-a354-4481-b918-706732e1405e"),
                            Price = 116.0,
                            Specialty = "Specialty 16",
                            UserId = "e1ce6150-1488-404b-9e32-636fbee7f133"
                        },
                        new
                        {
                            Id = new Guid("f17bdbd8-26b4-4e1e-be73-9114360bb881"),
                            Price = 117.0,
                            Specialty = "Specialty 17",
                            UserId = "b7c5a217-ca8f-430e-82bc-6b5228e4ffd9"
                        },
                        new
                        {
                            Id = new Guid("fb64d66d-adc7-45f6-918d-33060785c27d"),
                            Price = 118.0,
                            Specialty = "Specialty 18",
                            UserId = "ad16ed51-e493-49ad-a1ee-4c04707de040"
                        },
                        new
                        {
                            Id = new Guid("ce2b3ac0-85f1-4018-8a8e-2546ba347125"),
                            Price = 119.0,
                            Specialty = "Specialty 19",
                            UserId = "d5dd7440-fd7c-4ea2-a6e0-fad0d4ff3556"
                        },
                        new
                        {
                            Id = new Guid("a3f47e3f-eed3-40cf-9255-3aff83c64014"),
                            Price = 120.0,
                            Specialty = "Specialty 20",
                            UserId = "37d40e73-452e-4d21-83cd-a233c182a675"
                        });
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.FileImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("FileLength")
                        .HasColumnType("float");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PrescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("FileImages");
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modification_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e2058588-f4aa-43a3-884b-e9931f60956a"),
                            AppointmentId = new Guid("49908c9e-d1c6-4c18-b0f0-40327cf45dca"),
                            Description = "Prescription for appointment 1",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("3204a864-ad87-4227-bab5-3f0dceb08590"),
                            AppointmentId = new Guid("dd4bdfb7-a500-4ce2-8888-b449a268eb29"),
                            Description = "Prescription for appointment 2",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("6dd90d34-9af7-453f-8946-5b4adeb00adc"),
                            AppointmentId = new Guid("8a907523-ab91-408d-894e-800302e25591"),
                            Description = "Prescription for appointment 3",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("ffda7880-b053-4324-ba47-1021f3c2a203"),
                            AppointmentId = new Guid("45adfd40-9894-425e-9750-0d04e1fa31cf"),
                            Description = "Prescription for appointment 4",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("daac7753-b2ce-4c46-a2cb-d7a2ef1e1e96"),
                            AppointmentId = new Guid("b4c4b0e8-3ddb-405c-a2ad-de661735065b"),
                            Description = "Prescription for appointment 5",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("a64ae0d5-4806-483f-aa31-4dcf7d7ccc37"),
                            AppointmentId = new Guid("0543724f-5b29-4a27-b7c7-6a6665fc5c2e"),
                            Description = "Prescription for appointment 6",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("43280530-0277-4eec-86a1-75c64fe14a40"),
                            AppointmentId = new Guid("d4a65d73-7a7b-467e-b525-03389c3dd8df"),
                            Description = "Prescription for appointment 7",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("78d24d40-0fff-46ac-ac22-efa22f9a09e4"),
                            AppointmentId = new Guid("7e6f1328-0bb7-4245-866f-9e9bab8801a9"),
                            Description = "Prescription for appointment 8",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("3bcb737a-d69f-4031-a436-ca092842fffd"),
                            AppointmentId = new Guid("e768c293-9fc2-436f-896a-2be868e7e35d"),
                            Description = "Prescription for appointment 9",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("7fa9927c-96c7-49c6-a0f4-97e671360866"),
                            AppointmentId = new Guid("3ba70cd3-fa33-49c8-8d3b-bc3ebb5ab5e6"),
                            Description = "Prescription for appointment 10",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("412492d5-4111-4aca-9577-482ed1aa3668"),
                            AppointmentId = new Guid("14ccac34-95b0-4263-ad0a-691777ba05fd"),
                            Description = "Prescription for appointment 11",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("4ac0affb-7382-4e85-a514-95b7eb465a20"),
                            AppointmentId = new Guid("7ca31116-8dae-48d8-b0ea-53deda6916cb"),
                            Description = "Prescription for appointment 12",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("deec07b7-a289-4ac4-84fe-72a95ebc1cab"),
                            AppointmentId = new Guid("cec7123b-5f10-4a0b-9444-cc6fac7fff15"),
                            Description = "Prescription for appointment 13",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("34e518ca-6b7e-4f73-9248-98fe86c9155b"),
                            AppointmentId = new Guid("2d8947f4-de8c-48aa-9f46-664c51c82ccc"),
                            Description = "Prescription for appointment 14",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("7347daab-a080-490d-9723-69de3e11940e"),
                            AppointmentId = new Guid("bd590969-6632-4e59-8bc4-7722f64f7dbd"),
                            Description = "Prescription for appointment 15",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("f11fed2b-5506-4c03-be75-3ff4152d3c89"),
                            AppointmentId = new Guid("6ae2157d-1e58-4543-a7a6-8bb2cea19f86"),
                            Description = "Prescription for appointment 16",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("96cd8fc6-a897-454c-a6ea-e2e0d842c504"),
                            AppointmentId = new Guid("d3a060a8-b02a-4109-9fd0-158025c58cfd"),
                            Description = "Prescription for appointment 17",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("0f7e3ffe-d440-4663-8d8b-57cba195d0a2"),
                            AppointmentId = new Guid("6f0a43d4-4ac9-4dfe-9690-e136dc8a35ac"),
                            Description = "Prescription for appointment 18",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("2b2aa4ce-5beb-4856-abb8-e7ff7a0c7ee3"),
                            AppointmentId = new Guid("9545615a-c638-461a-9680-9883bfb3c59b"),
                            Description = "Prescription for appointment 19",
                            Modification_date = "2025-05-07"
                        },
                        new
                        {
                            Id = new Guid("9fda5945-3c8f-4645-90ef-37f93f692341"),
                            AppointmentId = new Guid("28481353-9f09-44c0-aeae-625e4200468f"),
                            Description = "Prescription for appointment 20",
                            Modification_date = "2025-05-07"
                        });
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.UserApplication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "155af4cd-9869-4ae2-bf58-5c743184adc9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6154583d-5433-4476-869f-004ce0a24304",
                            Email = "patient1@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT1@CLINIC.COM",
                            NormalizedUserName = "PATIENT1@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEM5OVfhQ22b5JEfILSWyIyiHe5DvXmf+Stj681xqeFDvpJDdSUaogZ8q+ygdqzjOGg==",
                            PhoneNumber = "01000000001",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "5f548e44-5494-438a-844a-c09b965cd650",
                            TwoFactorEnabled = false,
                            UserName = "patient1@clinic.com"
                        },
                        new
                        {
                            Id = "83519268-6998-43f9-b36e-52a61fd2ebea",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "73fa63bd-4bf4-4116-a3d3-4b3b4bb40605",
                            Email = "patient2@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT2@CLINIC.COM",
                            NormalizedUserName = "PATIENT2@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAgt603wL72x8SMAksOv7fQ0IMZCfas4nsN287358ermsvoZDG7+LiL9GazGNUi6yQ==",
                            PhoneNumber = "01000000002",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "a7a05b69-5f98-4d56-93d3-06dc4467b996",
                            TwoFactorEnabled = false,
                            UserName = "patient2@clinic.com"
                        },
                        new
                        {
                            Id = "0dd15ea2-0b87-4a71-a344-822c4f81c31b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4f795bbb-f4c1-42af-8e6a-570d3c9627f8",
                            Email = "patient3@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT3@CLINIC.COM",
                            NormalizedUserName = "PATIENT3@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOip256a89yocxldVKkzZ34m727moJeejBkwxBv/mOTLTv/1aSLIoEO8g0WE/fyn4g==",
                            PhoneNumber = "01000000003",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "d1ae3168-fb47-4cad-9d0b-1d4f9e7b68a9",
                            TwoFactorEnabled = false,
                            UserName = "patient3@clinic.com"
                        },
                        new
                        {
                            Id = "a4779ae0-81c9-46b7-b989-709460127449",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f967c5e9-dd5b-4908-b905-951e450efecf",
                            Email = "patient4@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT4@CLINIC.COM",
                            NormalizedUserName = "PATIENT4@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGnGTFzgi4CVx7Tp8w0V5TbOqgOraK6mrZpzVqxHon52TgHaZAvadMhijixAYN0W1w==",
                            PhoneNumber = "01000000004",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "c6973e65-6c05-428d-9aa2-7b362b58546f",
                            TwoFactorEnabled = false,
                            UserName = "patient4@clinic.com"
                        },
                        new
                        {
                            Id = "4e1b7bf2-f505-4c17-944b-4455e450adc2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b6e85fa0-bb5a-41ef-af05-0b06b4a4cc09",
                            Email = "patient5@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT5@CLINIC.COM",
                            NormalizedUserName = "PATIENT5@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECPbMdr7bCuELXj5eadQpJthtkeTmCrh8OR0PDD/Kgz2eAqcnDV2wTMjthj1QnykWw==",
                            PhoneNumber = "01000000005",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "b5e4cfa5-1c7c-4dd2-a4cd-041c49a8e127",
                            TwoFactorEnabled = false,
                            UserName = "patient5@clinic.com"
                        },
                        new
                        {
                            Id = "d13b4c2f-13ca-4f64-8ffc-9be8489b923e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "eb2f029c-21c0-4c2a-aaf3-5c6a7c68d814",
                            Email = "patient6@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT6@CLINIC.COM",
                            NormalizedUserName = "PATIENT6@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGw0ssQo5JSBfUHQAGZsrS84gDWzmChNkwM1nJAi2Nayg+69zDfA77NU7LhZmPXnfQ==",
                            PhoneNumber = "01000000006",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "db8fd649-a1fb-4e1d-88aa-d4e0491ac0cc",
                            TwoFactorEnabled = false,
                            UserName = "patient6@clinic.com"
                        },
                        new
                        {
                            Id = "1c163814-12e4-47d8-aa17-68bcbdbf897a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "98627825-bf99-4167-918d-87e0c86bde5d",
                            Email = "patient7@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT7@CLINIC.COM",
                            NormalizedUserName = "PATIENT7@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKBaGQ+/54ArO5Ubzz7Jt9GKlBxPS5qIxCoLnkFjOlVkdvqqWHaVI8Q5b4MN2J8xTQ==",
                            PhoneNumber = "01000000007",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "40bc8688-5a49-48bf-9b78-1397486ab0e8",
                            TwoFactorEnabled = false,
                            UserName = "patient7@clinic.com"
                        },
                        new
                        {
                            Id = "b728a214-1340-475f-b13a-c62e618669b2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ccf12655-7b06-4c85-a643-60d89498b30e",
                            Email = "patient8@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT8@CLINIC.COM",
                            NormalizedUserName = "PATIENT8@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEI9tOXTv7cesZleHxmeRLFnAQT90CLXYiO/U9+7AMjHytXK8Rsb17pi3q5laP/62/A==",
                            PhoneNumber = "01000000008",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "0b7784ac-4d54-4c19-9d54-b4af44fe16f2",
                            TwoFactorEnabled = false,
                            UserName = "patient8@clinic.com"
                        },
                        new
                        {
                            Id = "a9d51468-2a82-41cc-9503-2662a256a4b4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4b8441f8-051e-4be0-b9ba-ef7791e4ab0b",
                            Email = "patient9@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT9@CLINIC.COM",
                            NormalizedUserName = "PATIENT9@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIei6KW8m7fJeLcbnNxqeRYx0kZS5n3xJQyQDPABOKR8OQkVriYEEe2uGXctVMafAg==",
                            PhoneNumber = "01000000009",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "d8f0c810-1eec-43e2-8405-c1f9ca88f4dc",
                            TwoFactorEnabled = false,
                            UserName = "patient9@clinic.com"
                        },
                        new
                        {
                            Id = "4896696a-191d-4bdf-a628-55ec955890c8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f96d0d98-110f-4a19-b63d-d149d6486771",
                            Email = "patient10@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT10@CLINIC.COM",
                            NormalizedUserName = "PATIENT10@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEJN+pzoliv5xxeMMlQ+Aho/+UVpixZGHHCE/3G8HfTGLqLM8TboMuT2OjRmWgkF9w==",
                            PhoneNumber = "01000000010",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "969ae3fc-49ca-4ca8-b32d-fc8119e04d6a",
                            TwoFactorEnabled = false,
                            UserName = "patient10@clinic.com"
                        },
                        new
                        {
                            Id = "c69e9027-ee3b-456c-876f-209a391adafe",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "912a717c-43a8-4557-a26b-4a0ba65faff1",
                            Email = "patient11@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT11@CLINIC.COM",
                            NormalizedUserName = "PATIENT11@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBLpb4taZdZn9ZFm3saIKmz+ZCRTLRN3nCUqzekZsOj3LKj4197BarbPn8CLjt1lMA==",
                            PhoneNumber = "01000000011",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "6a9dbff0-9827-4e3f-9d24-1ee84f302b7d",
                            TwoFactorEnabled = false,
                            UserName = "patient11@clinic.com"
                        },
                        new
                        {
                            Id = "bbc7e4b4-8cd2-4ec9-8fc0-4d171783972d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "642df629-782d-4d10-bd75-4c17638ce02f",
                            Email = "patient12@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT12@CLINIC.COM",
                            NormalizedUserName = "PATIENT12@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMNryKYQoQruSOhCe2NLxN4LRGLJ1oIrdVGLHCSds4OFWRS8Deh+S2PCX0aXCCfU9w==",
                            PhoneNumber = "01000000012",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "8dbf7d02-c7ac-4b70-8ffe-ad01da587937",
                            TwoFactorEnabled = false,
                            UserName = "patient12@clinic.com"
                        },
                        new
                        {
                            Id = "d3d69fd0-f486-482d-a248-e4ef7ed938da",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2445318b-4708-41fd-81f4-090c45e5a1f0",
                            Email = "patient13@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT13@CLINIC.COM",
                            NormalizedUserName = "PATIENT13@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELdDR973FmH1+HotEh2BMwR4bnGD1GuI8Uisp/TdkBdengLVL7S4uY3+i/DuO+psgQ==",
                            PhoneNumber = "01000000013",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "548605b3-15a7-464a-826c-84d01b627b3d",
                            TwoFactorEnabled = false,
                            UserName = "patient13@clinic.com"
                        },
                        new
                        {
                            Id = "27bc3900-c570-42a9-968a-388cc321ce04",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "22d72e2e-22e6-4040-862a-55aa19a8f0bc",
                            Email = "patient14@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT14@CLINIC.COM",
                            NormalizedUserName = "PATIENT14@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBqHYS3pbJgDOdbemlkKGdMt+RXYQXeotH5ckDgFHkVoVuCJLSc1jNXkypP0ts3SKQ==",
                            PhoneNumber = "01000000014",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "06db4b99-8c94-4001-a4c9-a02502bcd343",
                            TwoFactorEnabled = false,
                            UserName = "patient14@clinic.com"
                        },
                        new
                        {
                            Id = "50583878-1af1-4c74-bc91-47bb6eb09889",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e4323992-6b90-42c4-b69c-10c10a4343b6",
                            Email = "patient15@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT15@CLINIC.COM",
                            NormalizedUserName = "PATIENT15@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPl3RiqrjMK3ifd7Ll9ZHunp2SFAY9NZHO2yt/3atnwTAI8Zs+Aj7v+xBO969fhUDw==",
                            PhoneNumber = "01000000015",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "2af2e0bc-9c0d-460d-93d8-a4e51024e9a3",
                            TwoFactorEnabled = false,
                            UserName = "patient15@clinic.com"
                        },
                        new
                        {
                            Id = "be8a8bb7-c229-467c-988b-5934ceaa1432",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d71e1dac-bd33-4bfa-bff0-7e1a08952f3e",
                            Email = "patient16@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT16@CLINIC.COM",
                            NormalizedUserName = "PATIENT16@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEM/4lWWJdFlIqeUJl6QlrVaH2/y14NCniHtsd6tETeazregiNOo5mb5Pu11uhpAuSw==",
                            PhoneNumber = "01000000016",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "5c9bcad8-32f8-4b8a-ad16-044fbee2ee5d",
                            TwoFactorEnabled = false,
                            UserName = "patient16@clinic.com"
                        },
                        new
                        {
                            Id = "1e04d179-7281-4106-8744-88dc51d83d78",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "01ff0d77-a20a-44f3-b518-669ade0c37b7",
                            Email = "patient17@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT17@CLINIC.COM",
                            NormalizedUserName = "PATIENT17@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ+vFdk0exYYe2zn/myTFobF7wo1iC1Cf5VAFDF5ssJ8+WwWD03FQDGnYP2eFvF/tw==",
                            PhoneNumber = "01000000017",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "c37d1d63-7d11-48de-a538-c46ffc6b25d4",
                            TwoFactorEnabled = false,
                            UserName = "patient17@clinic.com"
                        },
                        new
                        {
                            Id = "471ff9a6-382a-42d5-ae41-5350c22d3056",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "18a28e36-93e6-4b76-8fda-2ebaf93efe03",
                            Email = "patient18@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT18@CLINIC.COM",
                            NormalizedUserName = "PATIENT18@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMKdLQa9v8M6DlaCR2XEDLXX8c0J/mNc8QHnCBoGc66qcnMUuF+ZfKkyG3GaDjb/0g==",
                            PhoneNumber = "01000000018",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "17935b3c-9fd0-49db-a192-f32f43253ae3",
                            TwoFactorEnabled = false,
                            UserName = "patient18@clinic.com"
                        },
                        new
                        {
                            Id = "9ea01535-9542-444a-872f-08d09cb4b654",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a58e7f91-bf33-478e-9d9c-1c5254959afe",
                            Email = "patient19@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT19@CLINIC.COM",
                            NormalizedUserName = "PATIENT19@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHvZV/pa5iOO3QS4uR84p3f4bsXOnYjFF5e/CeMrhRTKCExICic4i0AYG4rPBCyceg==",
                            PhoneNumber = "01000000019",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "c887b94b-9340-4e2b-83ae-59281fc992f2",
                            TwoFactorEnabled = false,
                            UserName = "patient19@clinic.com"
                        },
                        new
                        {
                            Id = "3c429440-8760-40f6-9aa6-cfed9f0c197a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "01ac467c-b3b8-46a3-ba95-cc8a3d196508",
                            Email = "patient20@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT20@CLINIC.COM",
                            NormalizedUserName = "PATIENT20@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELljl5zOVRYcOGgtBAjVJrTHJeVgEGieEq0rMQow4Es3oX+3W8JElvfP0vjIAwjltw==",
                            PhoneNumber = "01000000020",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "e1908580-e95a-4aa8-8800-f79ccf0dbbd6",
                            TwoFactorEnabled = false,
                            UserName = "patient20@clinic.com"
                        },
                        new
                        {
                            Id = "54313667-8d2c-444e-8dc3-291a46c27d0c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "802301f2-23cb-401a-b1f8-a8d03cd6106d",
                            Email = "doctor1@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR1@CLINIC.COM",
                            NormalizedUserName = "DOCTOR1@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECilJ5gdJnXQIkeqlKRziTdFfuTj85B06rbe8YzxKfK52yM5JKcAK1knB1nKsOJkOA==",
                            PhoneNumber = "01100000001",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "26da348c-d340-4e05-ab69-d632c8a5073b",
                            TwoFactorEnabled = false,
                            UserName = "doctor1@clinic.com"
                        },
                        new
                        {
                            Id = "4bcbf4c1-97c3-4672-9613-73adec3ac42e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "88b6ae85-cc79-4803-adb2-b22c9b4808fe",
                            Email = "doctor2@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR2@CLINIC.COM",
                            NormalizedUserName = "DOCTOR2@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIN1RLVq1T42Xz0Unt0VLuWoBYxyMubZWDXvX37CzNlr1x91jMLws7bCmr/3ZM5rgg==",
                            PhoneNumber = "01100000002",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "93ac3fd9-8577-4184-ae57-547b7f12573e",
                            TwoFactorEnabled = false,
                            UserName = "doctor2@clinic.com"
                        },
                        new
                        {
                            Id = "3b98d85c-0738-4834-91d6-ff8243b6bb78",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e470f107-fb70-4442-afc4-a9fba7496a55",
                            Email = "doctor3@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR3@CLINIC.COM",
                            NormalizedUserName = "DOCTOR3@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEG4/sNh1MUs9Pn0Sr2FKFODVg1G3BpXr1lKsrbCc7tNmFhrkiMQ9glaU2chsLyThiA==",
                            PhoneNumber = "01100000003",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "dc4f666c-0c23-4174-909e-2f8e4f359861",
                            TwoFactorEnabled = false,
                            UserName = "doctor3@clinic.com"
                        },
                        new
                        {
                            Id = "388a7b3c-6bf5-4bed-a8e2-c94d4748ee73",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e895bb86-ed79-4e1f-bfa5-3d724e4cc067",
                            Email = "doctor4@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR4@CLINIC.COM",
                            NormalizedUserName = "DOCTOR4@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEF9d/j5qD9Wb78c3d9IjrwWPMQN0QakufpSOb2MvDQrpcmfemsuZDC407oEOpVrQ8w==",
                            PhoneNumber = "01100000004",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "158d2bef-44be-4a9d-9322-d45a2288022c",
                            TwoFactorEnabled = false,
                            UserName = "doctor4@clinic.com"
                        },
                        new
                        {
                            Id = "9e395a1b-9a82-46a2-8b36-7e11ea2afc8f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "02eb7f99-78b8-43f4-86fd-be1a68a03b4c",
                            Email = "doctor5@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR5@CLINIC.COM",
                            NormalizedUserName = "DOCTOR5@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEpdRAyCukzlpZJo5JOkBjhIpIbU2UWr9zmvZgqKVapHpzQfxWjRFSvNevICZJU/Bg==",
                            PhoneNumber = "01100000005",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "38d14990-a544-414c-893b-c8c25c51687d",
                            TwoFactorEnabled = false,
                            UserName = "doctor5@clinic.com"
                        },
                        new
                        {
                            Id = "332f34b3-de2d-4319-882a-d5b5e6257f31",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ae20e1e7-21cb-4746-a19c-db0678f9eeea",
                            Email = "doctor6@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR6@CLINIC.COM",
                            NormalizedUserName = "DOCTOR6@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMxZph5j0ingQLn+r/pTUv8uP3leV2Lcv/svU/kciF84hTvxcym2RVFmvVI8gcjZ6w==",
                            PhoneNumber = "01100000006",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "114338de-a517-470c-823e-9abd4580e030",
                            TwoFactorEnabled = false,
                            UserName = "doctor6@clinic.com"
                        },
                        new
                        {
                            Id = "48b56279-bb35-4703-92a4-4ae6788693e0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3e0bb603-edb9-4b8b-b1ab-41923855b9c5",
                            Email = "doctor7@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR7@CLINIC.COM",
                            NormalizedUserName = "DOCTOR7@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELWjMZo7ZSlQDqwaVc49QBftHH5HRqDZEePdOzOQu+Lz8z+Mgdiv8dwv0Sw3uZi2vg==",
                            PhoneNumber = "01100000007",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "dd67df17-132d-4b8f-be76-8563423ced64",
                            TwoFactorEnabled = false,
                            UserName = "doctor7@clinic.com"
                        },
                        new
                        {
                            Id = "cf6e8fc8-6d58-456e-86ca-c61a518f9636",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dc852e70-8b5a-4a5e-a679-d9a07763e86e",
                            Email = "doctor8@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR8@CLINIC.COM",
                            NormalizedUserName = "DOCTOR8@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMhb2CPIJgo064Js71bbIPX94JQgQhoP/L6qYfkXKc+rw3dUyIc0D9dC+ATbWcjEKA==",
                            PhoneNumber = "01100000008",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "e748de6b-0578-4a30-8f05-5eef59d41919",
                            TwoFactorEnabled = false,
                            UserName = "doctor8@clinic.com"
                        },
                        new
                        {
                            Id = "08fa64d7-4992-4b42-bc61-543bae5f14fe",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "73e78618-d196-44df-aafe-bb056c74f011",
                            Email = "doctor9@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR9@CLINIC.COM",
                            NormalizedUserName = "DOCTOR9@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELjz5NqgcJBHAeNl07MCwZXGNPBxmIZJoFAJUEMOmwH4qOHtzWoX4NERF0bUOfXIDw==",
                            PhoneNumber = "01100000009",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "855eac10-2f21-42fa-a129-2cda51861d85",
                            TwoFactorEnabled = false,
                            UserName = "doctor9@clinic.com"
                        },
                        new
                        {
                            Id = "239278b6-d460-46d5-a67b-65b2ea8bff56",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3ce45508-cc7a-4255-b7f2-be229250ae49",
                            Email = "doctor10@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR10@CLINIC.COM",
                            NormalizedUserName = "DOCTOR10@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENzSMNJ/43eJ0sNV9I9Ed+ENewNoG3OQViSSjmSPRSYfjsN/uCWXsGh2/f4K7bNRCQ==",
                            PhoneNumber = "01100000010",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "22e09971-2548-4703-be16-0f17190ab017",
                            TwoFactorEnabled = false,
                            UserName = "doctor10@clinic.com"
                        },
                        new
                        {
                            Id = "f8630862-4ec6-4b00-a1ad-10b319de03c1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "488810b8-55fb-486e-ad5d-089f5cb21286",
                            Email = "doctor11@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR11@CLINIC.COM",
                            NormalizedUserName = "DOCTOR11@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPqgdMboJH8OW+0IDSCmS44l9GLjdgiuNgE/Gbht2RMWa/ZGlC1WQUr+iTm9JRwdnA==",
                            PhoneNumber = "01100000011",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "6dae7221-4755-4352-8ce7-df8297ea68f4",
                            TwoFactorEnabled = false,
                            UserName = "doctor11@clinic.com"
                        },
                        new
                        {
                            Id = "208a800c-b8bc-4f7c-aa27-b1f5d1f75ce0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c7c22ebc-e261-490f-9507-9c624e62c226",
                            Email = "doctor12@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR12@CLINIC.COM",
                            NormalizedUserName = "DOCTOR12@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEM4p+J+e6MgFVlA7oMRTagfANLuY13suYNykV40yk6L7UG+2VWwnura6tkMzX0dn5w==",
                            PhoneNumber = "01100000012",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "0e3d4eb6-34f5-432b-9664-d42958d6fd44",
                            TwoFactorEnabled = false,
                            UserName = "doctor12@clinic.com"
                        },
                        new
                        {
                            Id = "9f27b9fb-1ba1-45ee-a85d-c3b190b2fc44",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6ef405f6-c0db-4091-ac27-a48860a294d9",
                            Email = "doctor13@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR13@CLINIC.COM",
                            NormalizedUserName = "DOCTOR13@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKi4ShXGTN0g1DV1BkUtgp/RRl+Xm0s9iDxG2OfxD8B39X2nSF73E60OKlrWCoBpPg==",
                            PhoneNumber = "01100000013",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "9c13269a-8bbe-4df7-a8bb-e4e97140b085",
                            TwoFactorEnabled = false,
                            UserName = "doctor13@clinic.com"
                        },
                        new
                        {
                            Id = "7ac5d4de-d0fd-4958-bc83-dd478b22e4f5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b122e653-f577-4237-831b-735483d3258e",
                            Email = "doctor14@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR14@CLINIC.COM",
                            NormalizedUserName = "DOCTOR14@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMvZbQvOk/QMRVgngMnS1ymmUPi458i+ovsX7fR6K6JgHgk8Hvibbgg2lML6zy2p3g==",
                            PhoneNumber = "01100000014",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "d09aaf19-6076-43e0-9fe7-2bfd0a988dd9",
                            TwoFactorEnabled = false,
                            UserName = "doctor14@clinic.com"
                        },
                        new
                        {
                            Id = "9c825ad4-18e1-4368-8dbc-329f78534d91",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "33419765-40ec-4c02-b4e6-ac259889baa1",
                            Email = "doctor15@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR15@CLINIC.COM",
                            NormalizedUserName = "DOCTOR15@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEImJyMUOMQ/rL/HYe3iCedS4SteSccdAldVlXZ8Ecm4RB0/CrNYvHfHgAxySv07KUQ==",
                            PhoneNumber = "01100000015",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "93b827e1-ad62-4d45-a595-31984744df63",
                            TwoFactorEnabled = false,
                            UserName = "doctor15@clinic.com"
                        },
                        new
                        {
                            Id = "e1ce6150-1488-404b-9e32-636fbee7f133",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d4a227c7-0d4e-4e62-8a2f-da429a1d41ce",
                            Email = "doctor16@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR16@CLINIC.COM",
                            NormalizedUserName = "DOCTOR16@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMY1IeeYlen7xYpY8m8EySaUyKM81Z4jSnq8eUZ39m7zRZTA2gT6YN8HOux4h+VGXA==",
                            PhoneNumber = "01100000016",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "dfb9d567-a281-4d65-af9c-251a9c45c741",
                            TwoFactorEnabled = false,
                            UserName = "doctor16@clinic.com"
                        },
                        new
                        {
                            Id = "b7c5a217-ca8f-430e-82bc-6b5228e4ffd9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aec11353-3841-4896-949c-aa110aba344e",
                            Email = "doctor17@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR17@CLINIC.COM",
                            NormalizedUserName = "DOCTOR17@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMFE/gG/RJ9OZ3+5Q5quHyV2ze2ncs0NPOYb/2Xq0mbK5rHw+enYeZwtkrfF6JCVAg==",
                            PhoneNumber = "01100000017",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "3c23ee73-1774-46c9-9b65-07724d96d1c4",
                            TwoFactorEnabled = false,
                            UserName = "doctor17@clinic.com"
                        },
                        new
                        {
                            Id = "ad16ed51-e493-49ad-a1ee-4c04707de040",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5ace0e88-02d4-4f2f-96d5-edb0feb13ec3",
                            Email = "doctor18@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR18@CLINIC.COM",
                            NormalizedUserName = "DOCTOR18@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHZyarj6koFPlcuxloJ2dfKPErD3dBNaduy7ZhQxJuKueA7jKMeQKvqqhtzixbvc2A==",
                            PhoneNumber = "01100000018",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "14ae7485-7e84-4163-9d24-c9f3244081b0",
                            TwoFactorEnabled = false,
                            UserName = "doctor18@clinic.com"
                        },
                        new
                        {
                            Id = "d5dd7440-fd7c-4ea2-a6e0-fad0d4ff3556",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "388d430a-b862-46c4-9b17-65e306a8ec8e",
                            Email = "doctor19@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR19@CLINIC.COM",
                            NormalizedUserName = "DOCTOR19@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFXgGryryHMhiq51HVDgOHh5nrvi1ZRHiVJerQ2Rk4DqFAWrbhfA1FvztBhU9bDJqg==",
                            PhoneNumber = "01100000019",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1defc95d-6215-42d2-952e-b5d785419da2",
                            TwoFactorEnabled = false,
                            UserName = "doctor19@clinic.com"
                        },
                        new
                        {
                            Id = "37d40e73-452e-4d21-83cd-a233c182a675",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3ca28c9e-d877-466b-83f4-224cc2f8476e",
                            Email = "doctor20@clinic.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR20@CLINIC.COM",
                            NormalizedUserName = "DOCTOR20@CLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOYMi5e9wx5mhBwlLYp6g1T8ojQhXpW1+nY5dXEMKbLNi2U9Au+UfJLZtGUMndKklw==",
                            PhoneNumber = "01100000020",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "d4d81e51-9127-43be-a7a3-9dffa4f9ce95",
                            TwoFactorEnabled = false,
                            UserName = "doctor20@clinic.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "675b578c-8739-4b1b-a706-816fb14910bd",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "72235979-4cb2-4bb1-9de9-9e931f98610e",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "155af4cd-9869-4ae2-bf58-5c743184adc9",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "83519268-6998-43f9-b36e-52a61fd2ebea",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "0dd15ea2-0b87-4a71-a344-822c4f81c31b",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "a4779ae0-81c9-46b7-b989-709460127449",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "4e1b7bf2-f505-4c17-944b-4455e450adc2",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "d13b4c2f-13ca-4f64-8ffc-9be8489b923e",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "1c163814-12e4-47d8-aa17-68bcbdbf897a",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "b728a214-1340-475f-b13a-c62e618669b2",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "a9d51468-2a82-41cc-9503-2662a256a4b4",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "4896696a-191d-4bdf-a628-55ec955890c8",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "c69e9027-ee3b-456c-876f-209a391adafe",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "bbc7e4b4-8cd2-4ec9-8fc0-4d171783972d",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "d3d69fd0-f486-482d-a248-e4ef7ed938da",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "27bc3900-c570-42a9-968a-388cc321ce04",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "50583878-1af1-4c74-bc91-47bb6eb09889",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "be8a8bb7-c229-467c-988b-5934ceaa1432",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "1e04d179-7281-4106-8744-88dc51d83d78",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "471ff9a6-382a-42d5-ae41-5350c22d3056",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "9ea01535-9542-444a-872f-08d09cb4b654",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "3c429440-8760-40f6-9aa6-cfed9f0c197a",
                            RoleId = "72235979-4cb2-4bb1-9de9-9e931f98610e"
                        },
                        new
                        {
                            UserId = "54313667-8d2c-444e-8dc3-291a46c27d0c",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "4bcbf4c1-97c3-4672-9613-73adec3ac42e",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "3b98d85c-0738-4834-91d6-ff8243b6bb78",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "388a7b3c-6bf5-4bed-a8e2-c94d4748ee73",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "9e395a1b-9a82-46a2-8b36-7e11ea2afc8f",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "332f34b3-de2d-4319-882a-d5b5e6257f31",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "48b56279-bb35-4703-92a4-4ae6788693e0",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "cf6e8fc8-6d58-456e-86ca-c61a518f9636",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "08fa64d7-4992-4b42-bc61-543bae5f14fe",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "239278b6-d460-46d5-a67b-65b2ea8bff56",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "f8630862-4ec6-4b00-a1ad-10b319de03c1",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "208a800c-b8bc-4f7c-aa27-b1f5d1f75ce0",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "9f27b9fb-1ba1-45ee-a85d-c3b190b2fc44",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "7ac5d4de-d0fd-4958-bc83-dd478b22e4f5",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "9c825ad4-18e1-4368-8dbc-329f78534d91",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "e1ce6150-1488-404b-9e32-636fbee7f133",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "b7c5a217-ca8f-430e-82bc-6b5228e4ffd9",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "ad16ed51-e493-49ad-a1ee-4c04707de040",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "d5dd7440-fd7c-4ea2-a6e0-fad0d4ff3556",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        },
                        new
                        {
                            UserId = "37d40e73-452e-4d21-83cd-a233c182a675",
                            RoleId = "2f1a1ad3-aa6b-4e9f-b6dc-9294e071a797"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Appointment", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Doctor", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", "userApplication")
                        .WithOne()
                        .HasForeignKey("ClinicAPI.Models.Domain.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userApplication");
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.FileImage", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.Doctor", "Doctor")
                        .WithMany("FileImages")
                        .HasForeignKey("DoctorId");

                    b.HasOne("ClinicAPI.Models.Domain.Prescription", "Prescription")
                        .WithMany("FileImage")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Doctor");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Prescription", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.Appointment", "Appointment")
                        .WithOne("Prescription")
                        .HasForeignKey("ClinicAPI.Models.Domain.Prescription", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ClinicAPI.Models.Domain.UserApplication", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Appointment", b =>
                {
                    b.Navigation("Prescription")
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("FileImages");
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.Prescription", b =>
                {
                    b.Navigation("FileImage");
                });

            modelBuilder.Entity("ClinicAPI.Models.Domain.UserApplication", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
